UbixOS: kernel/shutdown.c File Reference
shutdown.c File Reference
#include <sys/shutdown.h>
#include <sys/io.h>
#include <lib/kprintf.h>
Functions
int sys_shutdown (shutdownCMD_t cmd)
Function Documentation
sys_shutdown()
int sys_shutdown (shutdownCMD_t cmd)
Definition at line 34 of file shutdown.c.
References fl_shutdown(), HALT, inportByte(), kprintf(), outportByte(), and REBOOT.
Referenced by systemTask().