# (C) 2002-2026 The UbixOS Project

include ../../../../Makefile.incl
include ../../../Makefile.incl

INCLUDES += -I../../../include

OBJS = autoip.o dhcp.o etharp.o icmp.o igmp.o ip4.o ip4_addr.o ip4_frag.o

.include "${UBIX_MK}/ubix.kern.mk"
