UbixOS: include/ubixos/syscall.h File Reference
syscall.h File Reference
#include <sys/trap.h>
Functions
void _sys_call ()
int invalidCall ()
void invalidCallINT (int)
void sys_call (struct trapframe *frame)
Function Documentation
_sys_call()
void _sys_call ()
invalidCall()
int invalidCall ()
Definition at line 101 of file syscall.c.
References _current, taskStruct::id, kprintf(), and sys_call().
invalidCallINT()
void invalidCallINT (int)
sys_call()
void sys_call (struct trapframe * frame)
Definition at line 43 of file syscall.c.
References _current, thread::abi, die_if_kernel(), ELFOSABI_FREEBSD, thread::frame, taskStruct::id, kpanic(), kprintf(), PSL_C, syscall_entry::sc_name, SYSCALL_DUMMY, SYSCALL_INVALID, systemCalls, taskStruct::td, thread::td_retval, trapframe::tf_eax, trapframe::tf_edx, trapframe::tf_eflags, trapframe::tf_esp, and totalCalls.
Referenced by invalidCall(), and invalidCall_posix().