UbixOS: isa/pit.c File Reference
pit.c File Reference
#include <isa/pit.h>
#include <sys/io.h>
#include <lib/kprintf.h>
Functions
int pit_init ()
Function Documentation
pit_init()
int pit_init ()
Definition at line 62 of file pit.c.
References kprintf(), outportByte(), outportByteP(), and PIT_TIMER.