# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

OBJS = sStyle.o sTypes.o vContext.o vButton.o vMenuBar.o vView.o vCanvas.o vDesktop.o vTitleTab.o

INCLUDES += -I./include \
            -I../../objgfx40/objgfx40

OBJDIR = ${OBJ_DIR}/obj/gfx/sunlight

.include "${UBIX_MK}/ubix.sublib.mk"
