# bin/futextest/Makefile — end-to-end test for the futex syscall (Task D).

include ../../Makefile.incl
include ../Makefile.incl

BINARY = futextest

OBJS = main.o thread_asm.o

.include "${UBIX_MK}/ubix.musl.prog.mk"
