UbixOS: vmm/unmappage.c File Reference
unmappage.c File Reference
#include <vmm/vmm.h>
Functions
void vmm_unmapPage (uint32_t pageAddr, unmapFlags_t flags)
void vmm_unmapPages (void *ptr, uint32_t size, unmapFlags_t flags)
Function Documentation
vmm_unmapPage()
void vmm_unmapPage (uint32_t pageAddr, unmapFlags_t flags)
Definition at line 47 of file unmappage.c.
References freePage(), PAGE_PRESENT, PD_BASE_ADDR, and PT_BASE_ADDR.
Referenced by sys_mmap(), and vmm_createVirtualSpace().
vmm_unmapPages()
void vmm_unmapPages (void * ptr, uint32_t size, unmapFlags_t flags)
Definition at line 99 of file unmappage.c.
References PT_BASE_ADDR.
Referenced by sdeThread().