UbixOS: kernel/vfs_calls.c File Reference
vfs_calls.c File Reference
#include <ubixos/sched.h>
#include <sys/thread.h>
#include <sys/sysproto_posix.h>
#include <sys/descrip.h>
#include <sys/video.h>
#include <sys/pipe.h>
#include <sys/errno.h>
#include <string.h>
#include <ufs/ufs.h>
Functions
int kern_openat (struct thread *thr, int afd, char *path, int flags, int mode)
int sys_access (struct thread *td, struct sys_access_args *args)
int sys_close (struct thread *td, struct sys_close_args *args)
int sys_getdirentries (struct thread *td, struct sys_getdirentries_args *args)
int sys_open (struct thread *td, struct sys_open_args *args)
int sys_openat (struct thread *td, struct sys_openat_args *args)
int sys_pread (struct thread *td, struct sys_pread_args *args)
int sys_read (struct thread *td, struct sys_read_args *args)
int sys_readlink (struct thread *thr, struct sys_readlink_args *args)
int sys_unlink (struct thread *td, struct sys_unlink_args *uap)
int sys_write (struct thread *td, struct sys_write_args *uap)
Function Documentation
kern_openat()
int kern_openat (struct thread * thr, int afd, char * path, int flags, int mode)
Definition at line 397 of file vfs_calls.c.
References EINVAL, file::f_flag, falloc(), file::fd, fdestroy(), FFLAGS, FMASK, fopen(), kprintf(), O_ACCMODE, O_CREAT, O_EXEC, and thread::td_retval.
Referenced by sys_open().
sys_access()
int sys_access (struct thread * td, struct sys_access_args * args)
Definition at line 364 of file vfs_calls.c.
References thread::td_retval.
sys_close()
int sys_close (struct thread * td, struct sys_close_args * args)
Definition at line 94 of file vfs_calls.c.
References file::data, fclose(), file::fd, sys_close_args::fd, file::fd_type, fdestroy(), getfd(), kprintf(), thread::o_files, pipeInfo::rFD, pipeInfo::rfdCNT, thread::td_retval, pipeInfo::wFD, and pipeInfo::wfdCNT.
sys_getdirentries()
int sys_getdirentries (struct thread * td, struct sys_getdirentries_args * args)
Definition at line 371 of file vfs_calls.c.
References sys_getdirentries_args::buf, sys_getdirentries_args::count, DEV_BSIZE, file::fd, sys_getdirentries_args::fd, fread(), getfd(), and thread::td_retval.
sys_open()
int sys_open (struct thread * td, struct sys_open_args * args)
Definition at line 39 of file vfs_calls.c.
References AT_FDCWD, sys_open_args::flags, kern_openat(), kprintf(), sys_open_args::mode, and sys_open_args::path.
sys_openat()
int sys_openat (struct thread * td, struct sys_openat_args * args)
Definition at line 45 of file vfs_calls.c.
References falloc(), file::fd, fdestroy(), sys_openat_args::flag, fopen(), kprintf(), O_RDWR, O_WRONLY, sys_openat_args::path, and thread::td_retval.
sys_pread()
int sys_pread (struct thread * td, struct sys_pread_args * args)
Definition at line 237 of file vfs_calls.c.
References _current, sys_pread_args::buf, file::fd, sys_pread_args::fd, fread(), getchar(), getfd(), kprintf(), sys_pread_args::nbyte, fileDescriptor::offset, sys_pread_args::offset, sched_yield(), thread::td_retval, taskStruct::term, and tty_foreground.
sys_read()
int sys_read (struct thread * td, struct sys_read_args * args)
Definition at line 148 of file vfs_calls.c.
References _current, pipeInfo::bCNT, sys_read_args::buf, pipeBuf::buffer, file::data, sys_read_args::fd, file::fd, file::fd_type, fread(), getchar(), getfd(), pipeInfo::headPB, kfree(), kprintf(), memcpy(), sys_read_args::nbyte, pipeBuf::nbytes, pipeBuf::next, pipeBuf::offset, sched_yield(), thread::td_retval, taskStruct::term, and tty_foreground.
sys_readlink()
int sys_readlink (struct thread * thr, struct sys_readlink_args * args)
Definition at line 387 of file vfs_calls.c.
References sys_readlink_args::count, kprintf(), sys_readlink_args::path, and thread::td_retval.
sys_unlink()
int sys_unlink (struct thread * td, struct sys_unlink_args * uap)
Definition at line 449 of file vfs_calls.c.
References fl_remove(), kprintf(), sys_unlink_args::path, and thread::td_retval.
sys_write()
int sys_write (struct thread * td, struct sys_write_args * uap)
Definition at line 291 of file vfs_calls.c.
References pipeInfo::bCNT, sys_write_args::buf, pipeBuf::buffer, buffer, file::data, defaultColor, file::fd, sys_write_args::fd, file::fd_type, fwrite(), getfd(), pipeInfo::headPB, kfree(), kmalloc(), kprintf(), memcpy(), sys_write_args::nbyte, pipeBuf::nbytes, pipeBuf::next, thread::o_files, printColor, fileDescriptor::res, pipeInfo::tailPB, and thread::td_retval.