/*
 * config.h -- UbixOS/i386 hand-crafted configuration for tcsh 6.24.x
 *
 * Generated by hand for a musl-based cross-compiled i386 build.
 * Do not run ./configure — it won't work in a cross-compile environment.
 */

#ifndef _h_config
#define _h_config

/* Basic POSIX headers available in musl */
#define HAVE_DIRENT_H           1
#define HAVE_INTTYPES_H         1
#define HAVE_PATHS_H            1
#define HAVE_STDINT_H           1
#define HAVE_STDIO_H            1
#define HAVE_STDLIB_H           1
#define HAVE_STRING_H           1
#define HAVE_STRINGS_H          1
#define HAVE_SYS_STAT_H         1
#define HAVE_SYS_TYPES_H        1
#define HAVE_UNISTD_H           1
#define HAVE_WCHAR_H            1
#define HAVE_WCTYPE_H           1

/* Standard C */
#define STDC_HEADERS            1

/* POSIX functions available via musl */
#define HAVE_DUP2               1
#define HAVE_GETCWD             1
#define HAVE_GETHOSTNAME        1
#define HAVE_DECL_GETHOSTNAME   1
#define HAVE_DECL_CRYPT         1
/* No crypt/autologout locking — simplifies build */
#define NO_CRYPT                1
#define HAVE_GETPWENT           1
#define HAVE_MBLEN              1
#define HAVE_MBRTOWC            1
#define HAVE_MEMMOVE            1
#define HAVE_MEMSET             1
#define HAVE_MKSTEMP            1
#define HAVE_NICE               1
#define HAVE_SETPGID            1
#define HAVE_SETPRIORITY        1
#define HAVE_SYSCONF            1
#define HAVE_STRERROR           1
#define HAVE_STRCOLL            1
#define HAVE_STRSTR             1
#define HAVE_WCWIDTH            1
#define HAVE_LONG_LONG          1

/* UbixOS target identification */
#define UBIXOS                  1
#define TCSH_DBG(s) write(2, "[tcsh] " s "\n", sizeof("[tcsh] " s "\n") - 1)

/* devfs is mounted as devfs:, not under sys:/dev/ */
#define _PATH_DEVNULL           "devfs:/null"

/* Pull in time.h for time() declaration (musl sys/time.h does not imply it) */
#include <time.h>

/* POSIX mode — use termios.h, POSIX job control, etc. */
#define POSIX                   1
#define POSIXJOBS               1
#define BSDJOBS                 1
/* TERMIO: required so #ifdef TERMIO / #ifdef POSIX reaches the termios path */
#define TERMIO                  1
/* BSD timing and resource limits */
#define BSDTIMES                1
#define BSDLIMIT                1

/* getpgrp() / setpgrp() take no args on modern POSIX */
#define GETPGRP_VOID            1
#define SETPGRP_VOID            1

/* dirent has d_ino */
#define HAVE_STRUCT_DIRENT_D_INO 1

/* wchar_t is 4 bytes on i386 musl */
#define SIZEOF_WCHAR_T          4

/* Use system malloc — musl sbrk is not suitable for tc.alloc */
#define HAVE_WORKING_SBRK       0

/* No NLS/iconv — keeps things simple and avoids WIDE_STRINGS */
#undef NLS
#undef NLS_CATALOGS
#undef HAVE_ICONV
#undef HAVE_NL_LANGINFO

/* No utmp/utmpx on UbixOS */
#undef HAVE_UTMP_H
#undef HAVE_UTMPX_H

/* No shadow passwords */
#undef HAVE_SHADOW_H

/* No setproctitle */
#undef HAVE_SETPROCTITLE

/* No sbrk worth using */
#undef HAVE_SBRK

/* Package info */
#define PACKAGE_NAME            "tcsh"
#define PACKAGE_VERSION         "6.24.16"
#define PACKAGE_STRING          "tcsh 6.24.16"
#define PACKAGE_TARNAME         "tcsh"
#define PACKAGE_BUGREPORT       ""
#define PACKAGE_URL             ""

/* GETGROUPS_T — gid_t */
#define GETGROUPS_T             gid_t

#include "config_f.h"

/* UbixOS overrides — must come after config_f.h which may re-define these */
#undef REMOTEHOST           /* no remote login → no remote host detection needed */
#define OPEN_MAX 64         /* keep closem() fd scan short; matches RLIMIT_NOFILE */
#define NOFILE   64         /* direct override so tc.os.h fallback is skipped */

#endif /* _h_config */
