/* Do not edit this file, make creates it */
/* Hand-written for UbixOS/i386 — replaces the gethost-generated version. */
#include "sh.h"

void
getmachine(void)
{
    const char *hosttype;
    const char *ostype;
    const char *vendor;
    const char *machtype;

    hosttype = "i386-ubixos";
    vendor   = "unknown";
    ostype   = "ubixos";
    machtype = "i386";

    tsetenv(STRHOSTTYPE, str2short(hosttype));
    tsetenv(STRVENDOR,   str2short(vendor));
    tsetenv(STROSTYPE,   str2short(ostype));
    tsetenv(STRMACHTYPE, str2short(machtype));
} /* end getmachine */
