UbixOS: include/sys/shutdown.h File Reference
shutdown.h File Reference
Enumerations
enum shutdownCMD_t { HALT, REBOOT }
Functions
int sys_shutdown (shutdownCMD_t)
Enumeration Type Documentation
shutdownCMD_t
enum shutdownCMD_t
Enumerator
HALT
REBOOT
Definition at line 32 of file shutdown.h.
Function Documentation
sys_shutdown()
int sys_shutdown (shutdownCMD_t)
Definition at line 34 of file shutdown.c.
References fl_shutdown(), HALT, inportByte(), kprintf(), outportByte(), and REBOOT.
Referenced by systemTask().