# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

CFLAGS += -DBOOTPROG=\"MrOlsen\" -fno-builtin

OBJS = crc32.o gpt.o

.include "${UBIX_MK}/ubix.kern.mk"
