# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../include

OBJS = fprintf.o fseek.o printf.o vsprintf.o fd.o vfprintf.o fopen.o fread.o fwrite.o fdopen.o fgetc.o sprintf.o snprintf.o gets.o fclose.o fgets.o perror.o

.include "${UBIX_MK}/ubix.sublib.mk"
