UbixOS: include/ubixos/lists.h File Reference
lists.h File Reference
Data Structures
struct _item_t
struct _list_t
Macros
#define IN
#define STATUS_FAILURE -1
#define STATUS_SUCCESS 0
Typedefs
typedef struct _item_t Item_t
typedef struct _list_t List_t
Functions
Item_t * CreateItem ()
int DestroyItemList (List_t *ItemList)
int DestroyItemsInList (List_t *ItemList)
Item_t * GetFirstItem (List_t *kItem)
Item_t * GetLastItem (List_t *kItem)
List_t * InitializeList ()
int InsertItemAtFront (List_t *TList, Item_t *kItem)
int InsertItemBetweenItems (List_t *TList, Item_t *Previous, Item_t *Next, Item_t *Insert)
void InsertItemListBetweenItems (Item_t *Previous, Item_t *Next, List_t *Insert)
int RemoveItem (List_t *TList, Item_t *kItem)
List_t * RemoveItemListBetweenItems (Item_t *Previous, Item_t *Next)
Macro Definition Documentation
IN
#define IN
Definition at line 29 of file lists.h.
STATUS_FAILURE
#define STATUS_FAILURE -1
Definition at line 30 of file lists.h.
STATUS_SUCCESS
#define STATUS_SUCCESS 0
Definition at line 31 of file lists.h.
Typedef Documentation
Item_t
typedef struct _item_t Item_t
Definition at line 33 of file lists.h.
List_t
typedef struct _list_t List_t
Definition at line 34 of file lists.h.
Function Documentation
CreateItem()
Item_t* CreateItem ()
Referenced by kmod_add().
DestroyItemList()
int DestroyItemList (List_t * ItemList)
DestroyItemsInList()
int DestroyItemsInList (List_t * ItemList)
GetFirstItem()
Item_t* GetFirstItem (List_t * kItem)
GetLastItem()
Item_t* GetLastItem (List_t * kItem)
InitializeList()
List_t* InitializeList ()
Referenced by kmod_add().
InsertItemAtFront()
int InsertItemAtFront (List_t * TList, Item_t * kItem)
Referenced by kmod_add().
InsertItemBetweenItems()
int InsertItemBetweenItems (List_t * TList, Item_t * Previous, Item_t * Next, Item_t * Insert)
InsertItemListBetweenItems()
void InsertItemListBetweenItems (Item_t * Previous, Item_t * Next, List_t * Insert)
RemoveItem()
int RemoveItem (List_t * TList, Item_t * kItem)
RemoveItemListBetweenItems()
List_t* RemoveItemListBetweenItems (Item_t * Previous, Item_t * Next)