UbixOS: arch/i386/bioscall.c File Reference
bioscall.c File Reference
#include <sys/_null.h>
#include <sys/tss.h>
#include <ubixos/sched.h>
#include <vmm/vmm.h>
#include <lib/bioscall.h>
#include <string.h>
#include <sys/video.h>
#include <assert.h>
#include <lib/kprintf.h>
#include <vmm/paging.h>
Functions
void biosCall (int biosInt, int eax, int ebx, int ecx, int edx, int esi, int edi, int es, int ds)
Function Documentation
biosCall()
void biosCall (int biosInt, int eax, int ebx, int ecx, int edx, int esi, int edi, int es, int ds)
Definition at line 40 of file bioscall.c.
References _current, assert, tssStruct::back_link, bios16Code(), tssStruct::cr3, tssStruct::cs, tssStruct::ds, tssStruct::eax, tssStruct::ebp, tssStruct::ebx, tssStruct::ecx, tssStruct::edi, tssStruct::edx, EFLAG_IF, EFLAG_VM, tssStruct::eflags, tssStruct::eip, tssStruct::es, tssStruct::esi, tssStruct::esp, tssStruct::esp0, tssStruct::esp1, tssStruct::esp2, tssStruct::fs, tssStruct::gs, taskStruct::id, tssStruct::io_map, kernelPageDirectory, kmalloc(), kprintf(), tssStruct::ldt, taskStruct::oInfo, READY, sched_yield(), schedNewTask(), tssStruct::ss, tssStruct::ss0, tssStruct::ss1, tssStruct::ss2, taskStruct::state, tssStruct::trace_bitmap, taskStruct::tss, osInfo::v86Task, and vmm_getFreeKernelPage().