UbixOS: include/net/net.h File Reference
net.h File Reference
#include <sys/types.h>
#include <net/netif.h>
Functions
int net_init ()
Variables
struct netif lnc_netif
Function Documentation
net_init()
int net_init ()
Definition at line 52 of file init.c.
References ethernetif_init(), lnc_netif, lnc_thread(), netif_add(), netif_set_default(), netif_set_link_up(), netif_set_up(), NULL, shell_thread(), sys_thread_new(), tcpip_init(), and tcpip_input().
Variable Documentation
lnc_netif
struct netif lnc_netif
Definition at line 50 of file init.c.
Referenced by lnc_thread(), and net_init().