INCLUDES = -I../include -I../../../include.new
#CFLAGS = -fpic -DPIC -O2 -fno-strict-aliasing -pipe -D__DBINTERFACE_PRIVATE -DPOSIX_MISTAKE -DBROKEN_DES -DPORTMAP -DDES_BUILTIN -DYP -DHESIOD -Wsystem-headers -Wall -Wno-format-y2k -Wno-uninitialized
#CFLAGS += -DPORTMAP -D__DBINTERFACE_PRIVATE -nostdinc #-DPIC
