# (C) 2002-2026 The UbixOS Project

include ../../Makefile.incl
include ../Makefile.incl

OBJS = objgfx.o ogEdgeTable.o ogImage.o ogPixCon.o ogPixelFmt.o vWindow.o ogFont.o vWidget.o

INCLUDES += -I../../include

OBJDIR = ${OBJ_DIR}/obj/gfx/objgfx

.include "${UBIX_MK}/ubix.sublib.mk"
