# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../include

OBJS = mbrtowc.o srune.o none.o wcrtomb.o table.o runetype.o toupper.o tolower.o

.include "${UBIX_MK}/ubix.sublib.mk"
