KERNEL_SRC=${.CURDIR}
KERNEL_OBJ=${OBJ_DIR}${KERNEL_SRC}
KERNEL_CONF=${KERNEL_SRC}/${_ARCH}/conf
KERNEL_NAME=kernel
KERNEL_FLAGS=_ARCH=${_ARCH} CC="cc" CXX="c++" AS="as" AR="ar" LD="ld" NM=nm OBJDUMP= OBJCOPY="objcopy" RANLIB=ranlib
KERNEL_INC=${KERNEL_SRC}/include

KMAKE= ${MAKE} ${KERNEL_FLAGS} INCLUDE=${KERNEL_INC} KERNEL=${KERNEL_NAME}

INCLUDES = -I${INCLUDE}
CFLAGS = ${KFLAGS} -m32 -Wall -nostdlib -nostdinc -fno-builtin -fno-exceptions -ffreestanding -O
ROOT=/ubixos
