# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../../include

OBJS = ethernet.o ethernetif.o e1000netif.o ne2knetif.o
# loopif.o arp.o tcpdump.o

.include "${UBIX_MK}/ubix.kern.mk"
