UbixOS: include/ubixos/kpanic.h File Reference
kpanic.h File Reference
Macros
#define K_PANIC(msg) kpanic("Error: (%s), File: %s, Line: %i\n",msg ,__FILE__,__LINE__);
Functions
void kpanic (const char *fmt,...)
print panic message and halt system
Macro Definition Documentation
K_PANIC
#define K_PANIC (msg) kpanic("Error: (%s), File: %s, Line: %i\n",msg ,__FILE__,__LINE__);
Definition at line 32 of file kpanic.h.
Function Documentation
kpanic()
void kpanic (const char * fmt, ...)
print panic message and halt system
Parameters
fmt panic message
Definition at line 41 of file kpanic.c.
References irqDisable(), kprintf(), NULL, tty_foreground, va_end, va_start, and vsprintf().
Referenced by cpuidDetect(), cpuInfo(), execFile(), execThread(), fat_init(), kmod_load(), lnc_sendPacket(), PCtoNIC(), readUbixFS(), schedNewTask(), ogDisplay_UbixOS::SetMode(), sys_call(), sys_call_posix(), sys_mmap(), sysExec(), systemTask(), tcpdump_init(), tty_change(), ubthread_mutex_lock(), ubthread_mutex_unlock(), vitals_init(), vmm_allocPageTable(), vmm_findFreePage(), vmm_getFreeKernelPage(), vmm_remapPage(), and vmm_setPageAttributes().