# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../../include

OBJS = api_lib.o api_msg.o err.o sockets.o tcpip.o netbuf.o

.include "${UBIX_MK}/ubix.kern.mk"
