# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../include

OBJS = getcwd.o mkdir.o rmdir.o chdir.o

.include "${UBIX_MK}/ubix.sublib.mk"
