# (C) 2002-2026 The UbixOS Project

include ../../Makefile.incl
include ../Makefile.incl

OBJS = sem.o vfs_calls.o tty.o kern_sig.o pipe.o descrip.o kern_sysctl.o gen_calls.o endtask.o ld.o time.o elf.o ubthread.o vitals.o access.o syscall.o syscall_posix.o syscalls.o syscalls_posix.o execve.o kern_pipe.o shutdown.o sched_core.o fb.o klog.o signal.o

.include "${UBIX_MK}/ubix.kern.mk"
