# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I./include -I../locale

OBJS = swab.o strstr.o strspn.o strsep.o strpbrk.o strnstr.o strncpy.o strncmp.o strncat.o strmode.o strdup.o strcspn.o strcat.o strchr.o strcpy.o stpcpy.o memchr.o memccpy.o strcasecmp.o rindex.o index.o ffs.o bzero.o bcopy.o bcmp.o memmove.o strrchr.o strlcat.o strlcpy.o strerror.o strtok.o memcpy.o memset.o memcmp.o strlen.o strcmp.o strcasestr.o

.include "${UBIX_MK}/ubix.sublib.mk"
