UbixOS: include/ubixos/endtask.h File Reference
endtask.h File Reference
#include <sys/types.h>
#include <ubixos/sched.h>
Functions
void endTask (pidType)
Function Documentation
endTask()
void endTask (pidType)
Definition at line 44 of file endtask.c.
References DEAD, sched_setStatus(), and sched_yield().
Referenced by __alignmentCheck(), __debug(), __divideError(), __doubleFault(), __floatingPoint(), __machineCheck(), __nmi(), __security(), __simd(), __virtualization(), schedEndTask(), sys_exit(), and sysExec().