UbixOS: fs/vfs/mount.c File Reference
mount.c File Reference
#include <vfs/mount.h>
#include <ubixos/vitals.h>
#include <ubixos/kpanic.h>
#include <lib/kmalloc.h>
#include <lib/kprintf.h>
#include <string.h>
#include <sys/device.h>
Functions
int vfs_addMount (struct vfs_mountPoint *mp)
struct vfs_mountPoint * vfs_findMount (char *mountPoint)
int vfs_mount (int major, int minor, int partition, int vfsType, char *mountPoint, char *perms)
Function Documentation
vfs_addMount()
int vfs_addMount (struct vfs_mountPoint * mp)
Definition at line 102 of file mount.c.
References vitalsStruct::mountPoints, vfs_mountPoint::next, vfs_mountPoint::prev, and systemVitals.
Referenced by vfs_mount().
vfs_findMount()
struct vfs_mountPoint* vfs_findMount (char * mountPoint)
Definition at line 128 of file mount.c.
References vfs_mountPoint::mountPoint, vitalsStruct::mountPoints, vfs_mountPoint::next, NULL, strcmp(), and systemVitals.
Referenced by fopen().
vfs_mount()
int vfs_mount (int major, int minor, int partition, int vfsType, char * mountPoint, char * perms)
Definition at line 45 of file mount.c.
References vfs_mountPoint::device, device_find(), vfs_mountPoint::fs, kfree(), kmalloc(), kprintf(), device_node::minor, vfs_mountPoint::mountPoint, NULL, vfs_mountPoint::partition, vfs_mountPoint::perms, sprintf(), vfs_addMount(), vfsFindFS(), fileSystem::vfsInitFS, and fileSystem::vfsType.