UbixOS: vmm/copyvirtualspace.c File Reference
copyvirtualspace.c File Reference
#include <vmm/vmm.h>
#include <vmm/paging.h>
#include <sys/kern_sysctl.h>
#include <ubixos/spinlock.h>
#include <ubixos/kpanic.h>
#include <string.h>
Functions
void * vmm_copyVirtualSpace (pidType pid)
Function Documentation
vmm_copyVirtualSpace()
void* vmm_copyVirtualSpace (pidType pid)
Definition at line 51 of file copyvirtualspace.c.
References spinLock().
Referenced by fork_copyProcess(), and sys_fork().