# $Id: Makefile 89 2016-01-12 00:20:40Z reddawg $
# The System Makefile (C) 2002 The UbixOS Project

all: 
	(cd gen;make)
	(cd net;make)
	(cd stdlib;make)
	(cd string;make)
	(cd sys;make)
	(cd syscalls;make)

# Clean up the junk
clean:
	(cd gen;make clean)
	(cd net;make clean)
	(cd stdlib;make clean)
	(cd string;make clean)
	(cd sys;make clean)
	(cd syscalls;make clean)

