# (C) 2002-2026 The UbixOS Project
# 'lib' options

.include "${UBIX_MK}/ubix.platform.mk"

# Toolchain (CC/CXX/AS/AR/LD/NM/OBJCOPY/RANLIB) + TC_NOSTDINC/TC_STDFLAG come
# from ubix.toolchain.mk (set + exported by Makefile.incl).

LDFLAGS = -Bshareable

MUSL_SRC = ${SRCTOP}/contrib/musl
MUSL_OBJ = ${OBJ_DIR}/obj/musl
INCLUDES = -I${MUSL_SRC}/include \
           -I${MUSL_OBJ}/obj/include \
           -I${MUSL_SRC}/arch/${MUSL_ARCH} \
           -I${MUSL_SRC}/arch/generic \
           -I${SRCTOP}/include
CFLAGS = ${CROSS_M32} ${WFLAGS} -Wall -nostdlib ${TC_NOSTDINC} -fno-builtin -fno-exceptions -fno-rtti -O \
         ${ARCH_NOSIMD} -fPIC -MMD -MP
