# $Id: Makefile.inc 103 2016-01-12 05:32:24Z reddawg $
# 'lib' options

UNAME_S != uname -s
.if ${UNAME_S} == "Darwin"
CROSS_PREFIX?=x86_64-elf-
CROSS_M32?=-m32
.else
CROSS_PREFIX?=
CROSS_M32?=
.endif

CC=${CROSS_PREFIX}gcc
CXX=${CROSS_PREFIX}g++
AS=${CROSS_PREFIX}as
AR=${CROSS_PREFIX}ar
LD=${CROSS_PREFIX}ld
NM=${CROSS_PREFIX}nm
OBJCOPY=${CROSS_PREFIX}objcopy
RANLIB=${CROSS_PREFIX}ranlib

LDFLAGS = -Bshareable
#CFLAGS = -fpic -DPIC -O2 -fno-strict-aliasing -pipe -D__DBINTERFACE_PRIVATE -DPOSIX_MISTAKE -DBROKEN_DES -DPORTMAP -DDES_BUILTIN -DYP -DHESIOD -Wsystem-headers -Wall -Wno-format-y2k -Wno-uninitialized
CFLAGS = -m32 -fno-builtin -Wno-uninitialized -O2 -fno-strict-aliasing -pipe 

#INCLUDES = -I../include -I../i386
#INCLUDES = -I${INCLUDE}

INCLUDES = -I${SRCTOP}/include
CFLAGS = -m32 ${WFLAGS} -Wall -nostdlib -nostdinc -fno-builtin -fno-exceptions -O \
         -mno-sse -mno-sse2 -mno-mmx -mno-3dnow -fPIC
