# $Id: Makefile.inc 103 2016-01-12 05:32:24Z reddawg $
# 'lib' options

UNAME_S != uname -s
.if ${UNAME_S} == "Darwin"
CROSS_PREFIX?=x86_64-elf-
CROSS_M32?=-m32
.else
CROSS_PREFIX?=
CROSS_M32?=
.endif

CC=${CROSS_PREFIX}gcc
CXX=${CROSS_PREFIX}g++
AS=${CROSS_PREFIX}as
AR=${CROSS_PREFIX}ar
LD=${CROSS_PREFIX}ld
NM=${CROSS_PREFIX}nm
OBJCOPY=${CROSS_PREFIX}objcopy
RANLIB=${CROSS_PREFIX}ranlib

LDFLAGS = -Bshareable

MUSL_SRC = ${SRCTOP}/contrib/musl
MUSL_OBJ = ${OBJ_DIR}/obj/musl
INCLUDES = -I${MUSL_SRC}/include \
           -I${MUSL_OBJ}/obj/include \
           -I${MUSL_SRC}/arch/i386 \
           -I${MUSL_SRC}/arch/generic \
           -I${SRCTOP}/include
CFLAGS = -m32 ${WFLAGS} -Wall -nostdlib -nostdinc -fno-builtin -fno-exceptions -fno-rtti -O \
         -mno-sse -mno-sse2 -mno-mmx -mno-3dnow -fPIC -MMD -MP
