UbixOS: include/lib/kern_trie.h File Reference
kern_trie.h File Reference
#include <sys/types.h>
Data Structures
struct Trie
Macros
#define CHAR_SIZE 26
Functions
int delete_trieNode (struct Trie **, char *)
void insert_trieNode (struct Trie **, char *, void *)
struct Trie * new_trieNode ()
struct Trie * search_trieNode (struct Trie *, char *)
Macro Definition Documentation
CHAR_SIZE
#define CHAR_SIZE 26
Definition at line 34 of file kern_trie.h.
Function Documentation
delete_trieNode()
int delete_trieNode (struct Trie ** , char *)
Definition at line 99 of file kern_trie.c.
References haveChildren(), and NULL.
insert_trieNode()
void insert_trieNode (struct Trie ** , char * , void *)
Definition at line 46 of file kern_trie.c.
References Trie::character, Trie::e, Trie::isLeaf, new_trieNode(), and NULL.
new_trieNode()
struct Trie* new_trieNode ()
Definition at line 33 of file kern_trie.c.
References CHAR_SIZE, Trie::character, Trie::isLeaf, kmalloc(), and NULL.
Referenced by insert_trieNode().
search_trieNode()
struct Trie* search_trieNode (struct Trie * , char *)
Definition at line 70 of file kern_trie.c.
References Trie::character, and NULL.