UbixOS: include/lib/kprintf.h File Reference
kprintf.h File Reference
#include <sys/types.h>
#include <stdarg.h>
Macros
#define MAXNBUF 512
Functions
int kprintf (const char *,...)
int kvprintf (char const *fmt, void(*func)(int, void *), void *arg, int radix, va_list ap)
int ogPrintf (char *)
int sprintf (char *buf, const char *fmt,...)
Variables
int ogprintOff
int printOff
Macro Definition Documentation
MAXNBUF
#define MAXNBUF 512
Definition at line 35 of file kprintf.h.
Function Documentation
kprintf()
int kprintf (const char * , ...)
Definition at line 259 of file kprintf.c.
References kprint(), kvprintf(), NULL, ogPrintf(), ogprintOff, printOff, va_end, and va_start.
Referenced by __assert(), access(), addDirEntry(), apicMagic(), arp_arp_input(), biosCall(), close(), device_add(), die_if_kernel(), dup2(), execFile(), fat_initialize(), fcntl(), ffs_read(), fgetc(), fopen(), fork_copyProcess(), freebsd6_mmap(), fstat(), getdtablesize(), getfd(), getgid(), getpid(), gettimeofday_new(), getuid(), hdInit(), hdRead(), hdWrite(), i8259_init(), initLNC(), invalidCall(), invalidCall_posix(), InvalidSystemCall(), kern_openat(), kmod_add(), kmod_load(), kpanic(), ldEnable(), lnc_INT(), lnc_switchDWord(), lncAttach(), lncInt(), mouseHandler(), open_fat(), pci_init(), pciProbe(), pit_init(), qT(), read(), read_fat(), readlink(), sdeThread(), sem_init(), sys_call(), sys_call_posix(), sys_close(), sys_fopen(), sys_fseek(), sys_fwrite(), sys_getrlimit(), sys_invalid(), sys_ioctl(), sys_lseek(), sys_mpiPostMessage(), sys_open(), sys_openat(), sys_pread(), sys_read(), sys_readlink(), sys_sem_new(), sys_setrlimit(), sys_setsockopt(), sys_shutdown(), sys_sigprocmask(), sys_socket(), sys_sysarch(), sys_unlink(), sys_write(), sysAuth(), sysExec(), sysMkDir(), sysPasswd(), sysSDE(), systemTask(), ubixfs_initialize(), ubthread_mutex_lock(), ubthread_mutex_unlock(), ufs_writeFile(), vfs_init(), vfs_mount(), vitals_init(), vmm_pageFault(), vmm_pagingInit(), and write_fat().
kvprintf()
int kvprintf (char const * fmt, void(*)(int, void *) func, void * arg, int radix, va_list ap)
Definition at line 315 of file kprintf.c.
References MAXNBUF, NULL, PCHAR, uu::q, and va_arg.
Referenced by kprintf(), and sprintf().
ogPrintf()
int ogPrintf (char *)
Definition at line 40 of file ogprintf.cc.
References vitalsStruct::font, vitalsStruct::screen, and systemVitals.
Referenced by kprintf().
sprintf()
int sprintf (char * buf, const char * fmt, ...)
Definition at line 278 of file kprintf.c.
Referenced by fopen(), sys_chdir(), sys_fchdir(), sys_fstatfs(), sys_getcwd(), sys_statfs(), sysGetCwd(), sysMkDir(), ubixFSLoadDir(), ubixFSmkDir(), and vfs_mount().
Variable Documentation
ogprintOff
int ogprintOff
Definition at line 257 of file kprintf.c.
Referenced by kprintf(), sdeThread(), and systemTask().
printOff
int printOff
Definition at line 256 of file kprintf.c.
Referenced by kprintf(), sdeThread(), ogDisplay_UbixOS::SetMode(), and systemTask().