UbixOS: include/fat/fat.h File Reference
fat.h File Reference
Macros
#define FAT_PRINTF(a) kprintf a
Functions
int fat_init ()
Macro Definition Documentation
FAT_PRINTF
#define FAT_PRINTF (a) kprintf a
Definition at line 1 of file fat.h.
Function Documentation
fat_init()
int fat_init ()
Definition at line 180 of file fat.c.
References fat_initialize(), fl_init(), kpanic(), mkdir_fat(), NULL, open_fat(), read_fat(), unlink_fat(), vfsRegisterFS(), and write_fat().