UbixOS: sys/video.c File Reference
video.c File Reference
#include <sys/io.h>
#include <sys/video.h>
#include <ubixos/spinlock.h>
#include <ubixos/tty.h>
Functions
void backSpace ()
void clearScreen ()
void kprint (char *string)
Variables
int printColor = defaultColor
Function Documentation
backSpace()
void backSpace ()
Definition at line 37 of file video.c.
References inportByte(), and outportByte().
clearScreen()
void clearScreen ()
Definition at line 109 of file video.c.
kprint()
void kprint (char * string)
Definition at line 58 of file video.c.
References inportByte(), NULL, outportByte(), tty_find(), tty_foreground, and tty_print().
Referenced by kprintf().
Variable Documentation
printColor
int printColor = defaultColor
Definition at line 35 of file video.c.
Referenced by sys_write().