# (C) 2002-2026 The UbixOS Project

include ../../Makefile.incl
include ../Makefile.incl

OBJS = vmm_alloc_page_table.o page_fault.o vmm_page_fault.o vmm_get_free_virtual_page.o vmm_copy_virtual_space.o vmm_set_page_attributes.o vmm_unmap_page.o vmm_get_physical_addr.o vmm_get_free_page.o vmm_create_virtual_space.o vmm_memory.o vmm_paging.o vmm_init.o vmm_mmap.o vmm_free_virtual_page.o vmm_share_region.o vmm_swap.o vmm_pageout.o vm_map.o vm_filecache.o

.include "${UBIX_MK}/ubix.kern.mk"
