UbixOS: fs/fat/fat_format.h File Reference
fat_format.h File Reference
#include "fat_defs.h"
#include "fat_opts.h"
#include "fat_access.h"
Functions
int fatfs_format (struct fatfs *fs, uint32 volume_sectors, const char *name)
int fatfs_format_fat16 (struct fatfs *fs, uint32 volume_sectors, const char *name)
int fatfs_format_fat32 (struct fatfs *fs, uint32 volume_sectors, const char *name)
Function Documentation
fatfs_format()
int fatfs_format (struct fatfs * fs, uint32 volume_sectors, const char * name)
Definition at line 524 of file fat_format.c.
References fatfs_format_fat16(), fatfs_format_fat32(), and name.
Referenced by fl_format().
fatfs_format_fat16()
int fatfs_format_fat16 (struct fatfs * fs, uint32 volume_sectors, const char * name)
Definition at line 426 of file fat_format.c.
References FAT32_INVALID_CLUSTER, FAT_INIT_MEDIA_ACCESS_ERROR, FAT_TYPE_16, and fatfs_fat_init().
Referenced by fatfs_format().
fatfs_format_fat32()
int fatfs_format_fat32 (struct fatfs * fs, uint32 volume_sectors, const char * name)
Definition at line 475 of file fat_format.c.
References FAT32_INVALID_CLUSTER, FAT_INIT_MEDIA_ACCESS_ERROR, FAT_TYPE_32, and fatfs_fat_init().
Referenced by fatfs_format().