# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../include

OBJS = mpi.o startsde.o mmap.o error.o getuptime.o gettime.o getdrives.o setuid.o setgid.o getuid.o getgid.o exec.o getpid.o fork.o pidstatus.o getpage.o sched.o auth.o execve.o mpi_creatembox.o mpi_postmessage.o mpi_fetchmessage.o open.o dup2.o close.o setjmp.o uname.o sysctl.o read.o write.o stat.o wait.o exit.o access.o unlink.o lseek.o ioctl.o termios.o isatty.o

.include "${UBIX_MK}/ubix.sublib.mk"
