#!/bin/sh
# build.sh — cross-compile Git for uBixOS with the musl world toolchain.
#
# Git's hand-written Makefile is cross-friendly (its codegen is shell/perl, not
# compiled host helpers), so — unlike the dropbear port — we drive git's OWN
# Makefile rather than reimplementing the build.  The only real friction is the
# freestanding cross toolchain: aarch64-elf-gcc/x86_64-elf-gcc default to their
# bare-metal libc, so every compile needs -nostdinc + the musl include set, and
# every LINK needs -nostdlib plus musl crt objects, libc, libgcc and the dynamic
# linker threaded in the right positions.  git's link recipe has no post-$(LIBS)
# hook to append crtn, so we can't do it through LDFLAGS alone.  Instead CC is a
# generated WRAPPER (below) that classifies each invocation as compile-vs-link
# and injects the correct flags around git's own arguments — the same link line
# the world build uses (share/mk/ubix.musl.vars.mk).
#
# Invoked by Makefile with WRKSRC/CC/AR/LDEMUL/BUILD/MUSL_ARCH/PORTDIR/SRCTOP.
set -e
: "${WRKSRC:?}" "${CC:?}" "${AR:?}" "${LDEMUL:?}" "${BUILD:?}" "${MUSL_ARCH:?}" "${PORTDIR:?}" "${SRCTOP:?}"

MUSL="$SRCTOP/contrib/musl"
LIBGCC="$($CC -print-libgcc-file-name)"

# musl + shim + zlib include set (matches the dropbear/zlib ports).
MUSL_INC="-I$MUSL/include -I$BUILD/obj/musl/obj/include -I$MUSL/arch/$MUSL_ARCH -I$MUSL/arch/generic"
SHIM_INC="-I$PORTDIR/../bmake/shim"        # reuse the sys/cdefs.h shim
ZLIB_INC="-I$SRCTOP/contrib/zlib"

# ── Generate the CC wrapper ──────────────────────────────────────────────────
# A compile invocation carries -c/-E/-S; anything else is a link.  On compile we
# add -nostdinc + the musl headers; on link we add -nostdlib + crt + libc +
# libgcc + crtn + the dynamic linker, in glibc-crt order:
#   Scrt1 crti <user objs/flags> -lc libgcc crtn
WRAP="$WRKSRC/ubix-cc.sh"
cat > "$WRAP" <<EOF
#!/bin/sh
# generated by tools/ports/git/build.sh — do not edit
mode=link
for a in "\$@"; do case "\$a" in -c|-E|-S) mode=compile ;; esac; done
if [ "\$mode" = compile ]; then
	# git's own -I args (in "\$@") must precede the musl/system includes so a
	# bundled header like compat/regex/regex.h shadows musl's (which lacks
	# REG_STARTEND).  Project headers first, toolchain headers last.
	exec $CC -nostdinc -fno-builtin "\$@" $MUSL_INC $SHIM_INC $ZLIB_INC
fi
exec $CC -nostdlib -Wl,-m,$LDEMUL \\
	"$BUILD/obj/musl/lib/Scrt1.o" "$BUILD/obj/musl/lib/crti.o" \\
	"\$@" \\
	-L"$BUILD/lib" -lc "$LIBGCC" "$BUILD/obj/musl/lib/crtn.o" \\
	-Wl,-dynamic-linker,/lib/ld-musl-$MUSL_ARCH.so.1 -Wl,-rpath,/lib -pie
EOF
chmod +x "$WRAP"

# ── Drive git's Makefile ─────────────────────────────────────────────────────
cp "$PORTDIR/config.mak" "$WRKSRC/config.mak"
cd "$WRKSRC"

# The port worktree is shared across arches (not arch-homed); clear stale objects
# from a previous (possibly other-arch) run so this build starts clean.
make clean >/dev/null 2>&1 || true

# uname_S=UbixOS selects the empty (no-op) platform block; uname_M documents the
# arch.  CC=wrapper, AR=cross ar.  CFLAGS=-O2 (no -g) keeps the binary smaller.
# Build ONLY the multi-call `git` binary for M0 — skip the dashed helpers, test
# tooling and docs.
JOBS=$(sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 4)
make -j"$JOBS" \
	uname_S=UbixOS uname_M="$MUSL_ARCH" \
	CC="$WRAP" AR="$AR" CFLAGS="-O2 -std=gnu11 -fPIC" \
	git

echo "==> built $(ls -la "$WRKSRC/git" | awk '{print $5}') byte git binary"
