# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../../include

OBJS = sys_arch.o init.o shell.o
# shell.o udpecho.o init.o sys_arch.o bot.o

.include "${UBIX_MK}/ubix.kern.mk"
