# (C) 2002-2026 The UbixOS Project

include ../../Makefile.incl
include ../Makefile.incl

OBJS = objgfx40.o ogFont.o ogSprite.o ogPixCon.o ogPixelFmt.o

INCLUDES += -I./

OBJDIR = ${OBJ_DIR}/obj/gfx/objgfx40

.include "${UBIX_MK}/ubix.sublib.mk"
