# bin/tlstest/Makefile — end-to-end test for per-thread TLS (set_thread_area).

include ../../Makefile.incl
include ../Makefile.incl

BINARY = tlstest

OBJS = main.o tls_asm.o

.include "${UBIX_MK}/ubix.musl.prog.mk"
