# Host-platform + per-arch knobs (CROSS_PREFIX, CROSS_M32, MUSL_ARCH, ...).
.include "${UBIX_MK}/ubix.platform.mk"

CC=${CROSS_PREFIX}gcc
CXX=${CROSS_PREFIX}g++
AS=${CROSS_PREFIX}as
AR=${CROSS_PREFIX}ar
LD=${CROSS_PREFIX}ld
NM=${CROSS_PREFIX}nm
OBJCOPY=${CROSS_PREFIX}objcopy
RANLIB=${CROSS_PREFIX}ranlib

CFLAGS = ${CROSS_M32} -nostdlib -nostdinc -fno-builtin -Wno-unused-command-line-argument -fPIC -MMD -MP

MUSL_SRC = ${SRCTOP}/contrib/musl
MUSL_OBJ = ${OBJ_DIR}/obj/musl
INCLUDES = -I${MUSL_SRC}/include \
           -I${MUSL_OBJ}/obj/include \
           -I${MUSL_SRC}/arch/${MUSL_ARCH} \
           -I${MUSL_SRC}/arch/generic \
           -I${SRCTOP}/include

LIBRARIES =

STARTUP =
