UNAME_S != uname -s
.if ${UNAME_S} == "Darwin"
CROSS_PREFIX?=x86_64-elf-
CROSS_M32?=-m32
.else
CROSS_PREFIX?=
CROSS_M32?=
.endif

CC=${CROSS_PREFIX}gcc
CXX=${CROSS_PREFIX}g++
AS=${CROSS_PREFIX}as
AR=${CROSS_PREFIX}ar
LD=${CROSS_PREFIX}ld
NM=${CROSS_PREFIX}nm
OBJCOPY=${CROSS_PREFIX}objcopy
RANLIB=${CROSS_PREFIX}ranlib

CFLAGS = -m32 -nostdlib -nostdinc -fno-builtin -Wno-unused-command-line-argument -fPIC -MMD -MP

INCLUDES = -I../../include

LIBRARIES = ${OBJ_DIR}/obj/lib/*/*.o

STARTUP = ../../lib/ubix/*.o
