# bin/rndtest/Makefile — kernel CSPRNG test via getrandom(2) + /dev/urandom.
include ../../Makefile.incl
include ../Makefile.incl

BINARY = rndtest
OBJS   = main.o

.include "${UBIX_MK}/ubix.musl.prog.mk"
