# $FreeBSD: releng/11.1/lib/libc/tests/termios/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <ubix.own.mk>

NETBSD_ATF_TESTS_C=	tcsetpgrp_test

.include "../Makefile.netbsd-tests"

.include <ubix.test.mk>
