#	from @(#)Makefile.inc	8.2 (Berkeley) 2/21/94
Makefile.incl 156613 2006-03-13 01:15:01Z deischen $
#
CFLAGS+=-D__DBINTERFACE_PRIVATE

Makefile.incl"
Makefile.incl"
Makefile.incl"
Makefile.incl"
Makefile.incl"
Makefile.incl"

SYM_MAPS+=${.CURDIR}/db/Symbol.map
