UbixOS V2: C:/Dev/git/UbixOS/sys/include/isa/8259.h File Reference
8259.h File Reference
#include <sys/types.h>
Macros
#define eoi 0x20
#define icw1 0x11
#define icw4 0x01
#define mImr 0x21
#define mPic 0x20
#define mVec 0x68
#define ocw3Irr 0x0A
#define ocw3Isr 0x0B
#define sImr 0xA1
#define sPic 0xA0
#define sVec 0x70
Functions
int i8259_init ()
initialize the 8259 PIC
void irqDisable (uInt16 irqNo)
void irqEnable (uInt16 irqNo)
Macro Definition Documentation
eoi
#define eoi 0x20
Definition at line 38 of file 8259.h.
icw1
#define icw1 0x11
Definition at line 39 of file 8259.h.
icw4
#define icw4 0x01
Definition at line 40 of file 8259.h.
mImr
#define mImr 0x21
Definition at line 35 of file 8259.h.
mPic
#define mPic 0x20
Definition at line 34 of file 8259.h.
mVec
#define mVec 0x68
Definition at line 41 of file 8259.h.
ocw3Irr
#define ocw3Irr 0x0A
Definition at line 43 of file 8259.h.
ocw3Isr
#define ocw3Isr 0x0B
Definition at line 44 of file 8259.h.
sImr
#define sImr 0xA1
Definition at line 37 of file 8259.h.
sPic
#define sPic 0xA0
Definition at line 36 of file 8259.h.
sVec
#define sVec 0x70
Definition at line 42 of file 8259.h.
Function Documentation
i8259_init()
int i8259_init ()
initialize the 8259 PIC
This will initialize both PICs for all of our IRQs
Definition at line 41 of file 8259.c.
References icw1, icw4, kprintf(), mImr, mPic, mVec, outportByte(), sImr, sPic, and sVec.
irqDisable()
void irqDisable (uInt16 irqNo)
Referenced by kpanic().
irqEnable()
void irqEnable (uInt16 irqNo)
Referenced by fdc_init(), and initLNC().