UbixOS V2: C:/Dev/git/UbixOS/sys/arch/armv6/kpanic.c File Reference
kpanic.c File Reference
#include <ubixos/kpanic.h>
#include <lib/kprintf.h>
#include <isa/8259.h>
#include <stdarg.h>
#include <ubixos/tty.h>
Functions
void kpanic (const char *fmt,...)
print panic message and halt system
Function Documentation
kpanic()
void kpanic (const char * fmt, ...)
print panic message and halt system
Parameters
fmt panic message
Definition at line 41 of file kpanic.c.
Referenced by cpuidDetect(), cpuInfo(), execFile(), execThread(), fat_init(), kmod_load(), lnc_sendPacket(), PCtoNIC(), readUbixFS(), schedNewTask(), ogDisplay_UbixOS::SetMode(), sys_call(), sys_call_posix(), sys_mmap(), sysExec(), systemTask(), tcpdump_init(), tty_change(), ubthread_mutex_lock(), ubthread_mutex_unlock(), vitals_init(), vmm_allocPageTable(), vmm_findFreePage(), vmm_getFreeKernelPage(), vmm_remapPage(), and vmm_setPageAttributes().