UbixOS V2: C:/Dev/git/UbixOS/sys/arch/armv6/bioscall.c File Reference
bioscall.c File Reference
#include <sys/tss.h>
#include <ubixos/sched.h>
#include <vmm/vmm.h>
#include <lib/kmalloc.h>
#include <lib/bioscall.h>
#include <lib/string.h>
#include <sys/video.h>
#include <assert.h>
Functions
asm (".globl bios16Code\n" ".code16 \n" "bios16Code: \n" "int $0x10 \n" "int $0x69 \n" ".code32 \n")
void biosCall (int biosInt, int eax, int ebx, int ecx, int edx, int esi, int edi, int es, int ds)
Function Documentation
asm()
asm (".globl bios16Code\n" ".code16 \n" "bios16Code: \n" "int $0x10 \n" "int $0x69 \n" ".code32 \n")
biosCall()
void biosCall (int biosInt, int eax, int ebx, int ecx, int edx, int esi, int edi, int es, int ds)
Definition at line 49 of file bioscall.c.
Referenced by ogDisplay_UbixOS::GetModeInfo(), ogDisplay_UbixOS::GetVESAInfo(), initVESAMode(), and systemTask().