UbixOS V2: C:/Dev/git/UbixOS/sys/arch/armv6/sched.c File Reference
sched.c File Reference
#include <ubixos/sched.h>
#include <ubixos/kpanic.h>
#include <ubixos/spinlock.h>
#include <ubixos/endtask.h>
#include <vfs/mount.h>
#include <lib/kmalloc.h>
#include <lib/kprintf.h>
#include <vmm/vmm.h>
#include <sys/gdt.h>
#include <sys/idt.h>
#include <isa/8259.h>
#include <string.h>
#include <assert.h>
#include <sys/descrip.h>
Functions
void sched ()
int sched_addDelTask (kTask_t *tmpTask)
int sched_deleteTask (pidType id)
kTask_t * sched_getDelTask ()
int sched_init ()
int sched_setStatus (pidType pid, tState state)
void sched_yield ()
void schedEndTask (pidType pid)
kTask_t * schedFindTask (uInt32 id)
kTask_t * schedNewTask ()
Variables
kTask_t * _current = 0x0
kTask_t * _usedMath = 0x0
Function Documentation
sched()
void sched ()
Definition at line 80 of file sched.c.
Referenced by sched_yield().
sched_addDelTask()
int sched_addDelTask (kTask_t * tmpTask)
Definition at line 186 of file sched.c.
sched_deleteTask()
int sched_deleteTask (pidType id)
Definition at line 167 of file sched.c.
sched_getDelTask()
kTask_t* sched_getDelTask ()
Definition at line 195 of file sched.c.
Referenced by systemTask().
sched_init()
int sched_init ()
Definition at line 66 of file sched.c.
sched_setStatus()
int sched_setStatus (pidType pid, tState state)
Definition at line 265 of file sched.c.
Referenced by endTask(), execFile(), execThread(), and sys_wait4().
sched_yield()
void sched_yield ()
Definition at line 244 of file sched.c.
Referenced by __alignmentCheck(), __debug(), __divideError(), __doubleFault(), __floatingPoint(), __machineCheck(), __nmi(), __security(), __simd(), __virtualization(), biosCall(), endTask(), fork_copyProcess(), lnc_thread(), schedEndTask(), sdeTestThread(), sdeThread(), spinLock(), sys_fgetc(), sys_fork(), sys_pread(), sys_read(), sys_sched_yield(), sys_wait4(), sysSchedYield(), systemTask(), ubthread_cond_timedwait(), and ubthread_cond_wait().
schedEndTask()
void schedEndTask (pidType pid)
Definition at line 228 of file sched.c.
schedFindTask()
kTask_t* schedFindTask (uInt32 id)
Definition at line 207 of file sched.c.
Referenced by sched_setStatus(), sys_setpgid(), sys_wait4(), sysCheckPid(), and systemTask().
schedNewTask()
kTask_t* schedNewTask ()
Definition at line 135 of file sched.c.
Referenced by biosCall(), execFile(), execThread(), and sys_fork().
Variable Documentation
_current
kTask_t* _current = 0x0
Definition at line 50 of file sched.c.
Referenced by __alignmentCheck(), __debug(), __divideError(), __doubleFault(), __floatingPoint(), __machineCheck(), __nmi(), __security(), __simd(), __virtualization(), biosCall(), elf_load_file(), execFile(), fopen(), fork_copyProcess(), freebsd6_mmap(), fstat(), getgid(), getpid(), getuid(), in_group_p(), invalidCall(), invalidCall_posix(), kmod_load(), ldEnable(), lookup(), mathStateRestore(), pbuf_free(), permission(), schedEndTask(), sys_call(), sys_call_posix(), sys_chdir(), sys_exit(), sys_fchdir(), sys_fgetc(), sys_fork(), sys_fwrite(), sys_getcwd(), sys_getegid(), sys_getEUID(), sys_geteuid(), sys_getGID(), sys_getlogin(), sys_getpgrp(), sys_getpid(), sys_getppid(), sys_getUID(), sys_invalid(), sys_mmap(), sys_pread(), sys_read(), sys_setGID(), sys_setlogin(), sys_setpgid(), sys_setUID(), sys_wait4(), sysExec(), sysFwrite(), sysGetCwd(), sysGetFreePage(), sysGetGid(), sysGetpid(), sysGetUid(), sysMkDir(), sysPasswd(), sysSDE(), ubthread_mutex_lock(), ubthread_mutex_unlock(), ubthread_self(), and vmm_pageFault().
_usedMath
kTask_t* _usedMath = 0x0
Definition at line 51 of file sched.c.
Referenced by mathStateRestore().