UbixOS V2: C:/Dev/git/UbixOS/sys/fs/ubixfs/block.c File Reference
block.c File Reference
#include <ubixfs/ubixfs.h>
#include <vfs/file.h>
#include <vfs/mount.h>
Functions
int freeBlocks (int block, fileDescriptor_t *fd)
int getFreeBlocks (int count, fileDescriptor_t *fd)
void syncBat (struct vfs_mountPoint *mp)
Function Documentation
freeBlocks()
int freeBlocks (int block, fileDescriptor_t * fd)
Definition at line 78 of file block.c.
References blockAllocationTableEntry::attributes, ubixFSInfo::blockAllocationTable, vfs_mountPoint::fsInfo, fileDescriptor::mp, blockAllocationTableEntry::nextBlock, and syncBat().
getFreeBlocks()
int getFreeBlocks (int count, fileDescriptor_t * fd)
Definition at line 95 of file block.c.
References blockAllocationTableEntry::attributes, ubixFSInfo::batEntries, ubixFSInfo::blockAllocationTable, vfs_mountPoint::fsInfo, fileDescriptor::mp, blockAllocationTableEntry::nextBlock, and syncBat().
Referenced by ubixFSmkDir(), and writeUbixFS().
syncBat()
void syncBat (struct vfs_mountPoint * mp)
Definition at line 73 of file block.c.
References ubixFSInfo::blockAllocationTable, vfs_mountPoint::device, device_node::devInfo, vfs_mountPoint::diskLabel, vfs_mountPoint::fsInfo, device_interface::info, vfs_mountPoint::partition, ubixDiskLabel::partitions, ubixDiskLabel::ubixPartitions::pBatSize, ubixDiskLabel::ubixPartitions::pOffset, and device_interface::write.
Referenced by freeBlocks(), and getFreeBlocks().