UbixOS V2: C:/Dev/git/UbixOS/sys/net/core/init.c File Reference
init.c File Reference
#include "net/opt.h"
#include <ubixos/sem.h>
#include "net/init.h"
#include "net/stats.h"
#include "net/sys.h"
#include "net/mem.h"
#include "net/memp.h"
#include "net/pbuf.h"
#include "net/netif.h"
#include "net/sockets.h"
#include "net/ip.h"
#include "net/raw.h"
#include "net/udp.h"
#include "net/priv/tcp_priv.h"
#include "net/igmp.h"
#include "net/dns.h"
#include "net/timeouts.h"
#include "net/etharp.h"
#include "net/ip6.h"
#include "net/nd6.h"
#include "net/mld6.h"
#include "net/api.h"
#include "netif/ppp/ppp_opts.h"
#include "netif/ppp/ppp_impl.h"
Data Structures
struct packed_struct_test
Macros
#define LWIP_DISABLE_MEMP_SANITY_CHECKS 0
#define LWIP_DISABLE_TCP_SANITY_CHECKS 0
#define PACKED_STRUCT_TEST_EXPECTED_SIZE 5
Functions
void lwip_init (void)
Variables
PACK_STRUCT_BEGIN struct packed_struct_test PACK_STRUCT_STRUCT
Macro Definition Documentation
LWIP_DISABLE_MEMP_SANITY_CHECKS
#define LWIP_DISABLE_MEMP_SANITY_CHECKS 0
Definition at line 270 of file init.c.
LWIP_DISABLE_TCP_SANITY_CHECKS
#define LWIP_DISABLE_TCP_SANITY_CHECKS 0
Definition at line 267 of file init.c.
PACKED_STRUCT_TEST_EXPECTED_SIZE
#define PACKED_STRUCT_TEST_EXPECTED_SIZE 5
Definition at line 75 of file init.c.
Function Documentation
lwip_init()
void lwip_init (void)
Initialize all modules. Use this in NO_SYS mode. Use tcpip_init() otherwise.
Definition at line 333 of file init.c.
References LWIP_ASSERT, LWIP_CONST_CAST, LWIP_UNUSED_ARG, mem_init(), memp_init(), netif_init(), PACKED_STRUCT_TEST_EXPECTED_SIZE, pbuf_init, stats_init, and sys_init().
Referenced by tcpip_init().
Variable Documentation
PACK_STRUCT_STRUCT
PACK_STRUCT_BEGIN struct packed_struct_test PACK_STRUCT_STRUCT