UbixOS V2: C:/Dev/git/UbixOS/sys/include/ubixos/exec.h File Reference
exec.h File Reference
#include <sys/types.h>
#include <ubixos/sched.h>
Functions
void execFile (char *file, char **argv, char **envp, int console)
uint32_t execThread (void(*tproc)(void), uint32_t, char *)
int sys_exec (struct thread *, char *, char **, char **)
Function Documentation
execFile()
void execFile (char * file, char ** argv, char ** envp, int console)
Definition at line 244 of file i386_exec.c.
execThread()
uint32_t execThread (void(*)(void) tproc, uint32_t , char *)
Definition at line 148 of file i386_exec.c.
References assert, tssStruct::back_link, tssStruct::cr3, tssStruct::cs, tssStruct::ds, tssStruct::ebp, tssStruct::edi, tssStruct::eflags, tssStruct::eip, tssStruct::es, tssStruct::esi, tssStruct::esp, tssStruct::esp0, tssStruct::esp1, tssStruct::esp2, taskStruct::files, tssStruct::fs, tssStruct::gs, taskStruct::id, tssStruct::io_map, kernelPageDirectory, kpanic(), tssStruct::ldt, taskStruct::oInfo, PAGE_SIZE, READY, sched_setStatus(), schedNewTask(), tssStruct::ss, tssStruct::ss0, tssStruct::ss1, tssStruct::ss2, tssStruct::trace_bitmap, taskStruct::tss, vmm_getFreeKernelPage(), and osInfo::vmStart.
sys_exec()
int sys_exec (struct thread * , char * , char ** , char **)
Clean the virtual of COW pages left over from the fork
Definition at line 491 of file i386_exec.c.