UbixOS V2: C:/Dev/git/UbixOS/sys/fs/fat/fat_string.h File Reference
fat_string.h File Reference
Macros
#define NULL 0
Functions
int fatfs_compare_names (char *strA, char *strB)
int fatfs_create_path_string (char *path, char *filename, char *out, int maxlen)
int fatfs_get_extension (char *filename, char *out, int maxlen)
int fatfs_get_sfn_display_name (char *out, char *in)
int fatfs_get_substring (char *Path, int levelreq, char *output, int max_len)
int fatfs_split_path (char *FullPath, char *Path, int max_path, char *FileName, int max_filename)
int fatfs_string_ends_with_slash (char *path)
int fatfs_total_path_levels (char *path)
Macro Definition Documentation
NULL
#define NULL 0
Definition at line 17 of file fat_string.h.
Function Documentation
fatfs_compare_names()
int fatfs_compare_names (char * strA, char * strB)
Definition at line 260 of file fat_string.c.
References NULL.
Referenced by fatfs_get_file_entry().
fatfs_create_path_string()
int fatfs_create_path_string (char * path, char * filename, char * out, int maxlen)
Definition at line 403 of file fat_string.c.
fatfs_get_extension()
int fatfs_get_extension (char * filename, char * out, int maxlen)
Definition at line 370 of file fat_string.c.
fatfs_get_sfn_display_name()
int fatfs_get_sfn_display_name (char * out, char * in)
Definition at line 345 of file fat_string.c.
Referenced by fatfs_list_directory_next().
fatfs_get_substring()
int fatfs_get_substring (char * Path, int levelreq, char * output, int max_len)
Definition at line 92 of file fat_string.c.
References strlen().
Referenced by fatfs_split_path().
fatfs_split_path()
int fatfs_split_path (char * FullPath, char * Path, int max_path, char * FileName, int max_filename)
Definition at line 151 of file fat_string.c.
References fatfs_get_substring(), fatfs_total_path_levels(), memcpy(), and strlen().
fatfs_string_ends_with_slash()
int fatfs_string_ends_with_slash (char * path)
Definition at line 323 of file fat_string.c.
fatfs_total_path_levels()
int fatfs_total_path_levels (char * path)
Definition at line 44 of file fat_string.c.
Referenced by fatfs_split_path().