UbixOS V2: C:/Dev/git/UbixOS/sys/kernel/gen_calls.c File Reference
gen_calls.c File Reference
#include <sys/gen_calls.h>
#include <sys/thread.h>
#include <sys/gdt.h>
#include <ubixos/sched.h>
#include <ubixos/endtask.h>
#include <lib/kprintf.h>
#include <lib/kmalloc.h>
#include <string.h>
#include <assert.h>
#include <sys/descrip.h>
#include <sys/video.h>
#include <sys/signal.h>
#include <ubixos/errno.h>
#include <vmm/vmm.h>
Functions
int access (struct thread *td, struct access_args *uap)
int getgid (struct thread *td, struct getgid_args *uap)
int getpid (struct thread *td, struct getpid_args *uap)
int gettimeofday_new (struct thread *td, struct gettimeofday_args *uap)
int getuid (struct thread *td, struct getuid_args *uap)
int mprotect (struct thread *td, struct mprotect_args *uap)
int read (struct thread *td, struct read_args *uap)
int readlink (struct thread *td, struct readlink_args *uap)
int setitimer (struct thread *td, struct setitimer_args *uap)
place holder for now functionality to be added later
int sys_exit (struct thread *td, struct sys_exit_args *args)
int sys_getegid (struct thread *td, struct sys_getegid_args *args)
int sys_geteuid (struct thread *td, struct sys_geteuid_args *args)
int sys_getlogin (struct thread *thr, struct sys_getlogin_args *args)
int sys_getpgrp (struct thread *td, struct sys_getpgrp_args *args)
int sys_getpid (struct thread *td, struct sys_getpid_args *args)
int sys_getppid (struct thread *td, struct sys_getppid_args *args)
int sys_getrlimit (struct thread *thr, struct sys_getrlimit_args *args)
int sys_gettimeofday (struct thread *td, struct sys_gettimeofday_args *args)
int sys_invalid (struct thread *td, void *args)
int sys_issetugid (register struct thread *td, struct sys_issetugid_args *uap)
int sys_setlogin (struct thread *thr, struct sys_setlogin_args *args)
int sys_setpgid (struct thread *td, struct sys_setpgid_args *args)
int sys_setrlimit (struct thread *thr, struct sys_setrlimit_args *args)
int sys_sigaction (struct thread *td, struct sys_sigaction_args *args)
int sys_sigprocmask (struct thread *td, struct sys_sigprocmask_args *args)
int sys_sysarch (struct thread *td, struct sys_sysarch_args *args)
int sys_wait4 (struct thread *td, struct sys_wait4_args *args)
Function Documentation
access()
int access (struct thread * td, struct access_args * uap)
Definition at line 130 of file gen_calls.c.
References kprintf(), and access_args::path.
getgid()
int getgid (struct thread * td, struct getgid_args * uap)
Definition at line 70 of file gen_calls.c.
References _current, taskStruct::gid, kprintf(), and thread::td_retval.
getpid()
int getpid (struct thread * td, struct getpid_args * uap)
Definition at line 52 of file gen_calls.c.
References _current, taskStruct::id, kprintf(), and thread::td_retval.
gettimeofday_new()
int gettimeofday_new (struct thread * td, struct gettimeofday_args * uap)
Definition at line 93 of file gen_calls.c.
References kprintf().
getuid()
int getuid (struct thread * td, struct getuid_args * uap)
Definition at line 61 of file gen_calls.c.
References _current, kprintf(), thread::td_retval, and taskStruct::uid.
mprotect()
int mprotect (struct thread * td, struct mprotect_args * uap)
Definition at line 136 of file gen_calls.c.
read()
int read (struct thread * td, struct read_args * uap)
Definition at line 100 of file gen_calls.c.
References read_args::buf, file::fd, read_args::fd, fread(), getfd(), kprintf(), read_args::nbyte, and thread::td_retval.
Referenced by dmaXfer(), and fdcRw().
readlink()
int readlink (struct thread * td, struct readlink_args * uap)
Definition at line 83 of file gen_calls.c.
References readlink_args::count, kprintf(), readlink_args::path, and thread::td_retval.
setitimer()
int setitimer (struct thread * td, struct setitimer_args * uap)
place holder for now functionality to be added later
Definition at line 124 of file gen_calls.c.
sys_exit()
int sys_exit (struct thread * td, struct sys_exit_args * args)
Definition at line 45 of file gen_calls.c.
References _current, endTask(), and taskStruct::id.
sys_getegid()
int sys_getegid (struct thread * td, struct sys_getegid_args * args)
Definition at line 233 of file gen_calls.c.
References _current, taskStruct::gid, and thread::td_retval.
sys_geteuid()
int sys_geteuid (struct thread * td, struct sys_geteuid_args * args)
Definition at line 228 of file gen_calls.c.
References _current, thread::td_retval, and taskStruct::uid.
sys_getlogin()
int sys_getlogin (struct thread * thr, struct sys_getlogin_args * args)
Definition at line 360 of file gen_calls.c.
References _current, memcpy(), sys_getlogin_args::namebuf, sys_getlogin_args::namelen, and taskStruct::username.
sys_getpgrp()
int sys_getpgrp (struct thread * td, struct sys_getpgrp_args * args)
Definition at line 310 of file gen_calls.c.
References _current, taskStruct::pgrp, and thread::td_retval.
sys_getpid()
int sys_getpid (struct thread * td, struct sys_getpid_args * args)
Definition at line 224 of file gen_calls.c.
References _current, taskStruct::id, and thread::td_retval.
sys_getppid()
int sys_getppid (struct thread * td, struct sys_getppid_args * args)
Definition at line 238 of file gen_calls.c.
References _current, taskStruct::ppid, and thread::td_retval.
sys_getrlimit()
int sys_getrlimit (struct thread * thr, struct sys_getrlimit_args * args)
Definition at line 376 of file gen_calls.c.
References kprintf(), thread::rlim, rlimit::rlim_cur, rlimit::rlim_max, sys_getrlimit_args::rlp, and sys_getrlimit_args::which.
sys_gettimeofday()
int sys_gettimeofday (struct thread * td, struct sys_gettimeofday_args * args)
Definition at line 354 of file gen_calls.c.
References gettimeofday(), thread::td_retval, sys_gettimeofday_args::tp, and sys_gettimeofday_args::tzp.
sys_invalid()
int sys_invalid (struct thread * td, void * args)
Definition at line 141 of file gen_calls.c.
References _current, thread::frame, taskStruct::id, kprintf(), thread::td_retval, and trapframe::tf_eax.
sys_issetugid()
int sys_issetugid (register struct thread * td, struct sys_issetugid_args * uap)
Definition at line 78 of file gen_calls.c.
References thread::td_retval.
sys_setlogin()
int sys_setlogin (struct thread * thr, struct sys_setlogin_args * args)
Definition at line 368 of file gen_calls.c.
References _current, memcpy(), sys_setlogin_args::namebuf, and taskStruct::username.
sys_setpgid()
int sys_setpgid (struct thread * td, struct sys_setpgid_args * args)
Definition at line 315 of file gen_calls.c.
References _current, taskStruct::id, sys_setpgid_args::pgid, taskStruct::pgrp, sys_setpgid_args::pid, schedFindTask(), and thread::td_retval.
sys_setrlimit()
int sys_setrlimit (struct thread * thr, struct sys_setrlimit_args * args)
Definition at line 450 of file gen_calls.c.
References kprintf(), thread::rlim, rlimit::rlim_cur, rlimit::rlim_max, sys_setrlimit_args::rlp, and sys_setrlimit_args::which.
sys_sigaction()
int sys_sigaction (struct thread * td, struct sys_sigaction_args * args)
Definition at line 294 of file gen_calls.c.
References sys_sigaction_args::act, memcpy(), sys_sigaction_args::oact, sys_sigaction_args::sig, thread::sigact, and thread::td_retval.
sys_sigprocmask()
int sys_sigprocmask (struct thread * td, struct sys_sigprocmask_args * args)
Definition at line 243 of file gen_calls.c.
References __sigset::__bits, sys_sigprocmask_args::how, kprintf(), memcpy(), sys_sigprocmask_args::oset, sys_sigprocmask_args::set, SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK, thread::sigmask, and thread::td_retval.
sys_sysarch()
int sys_sysarch (struct thread * td, struct sys_sysarch_args * args)
Definition at line 186 of file gen_calls.c.
References gdtDescriptor::access, gdtDescriptor::baseHigh, gdtDescriptor::baseLow, gdtDescriptor::baseMed, dBig, dBiglim, dData, dDpl3, dPresent, dWrite, gdtDescriptor::granularity, kprintf(), gdtDescriptor::limitHigh, gdtDescriptor::limitLow, sys_sysarch_args::op, sys_sysarch_args::parms, thread::td_retval, and VMM_USER_LDT.
sys_wait4()
int sys_wait4 (struct thread * td, struct sys_wait4_args * args)
Definition at line 147 of file gen_calls.c.
References _current, taskStruct::children, ECHILD, taskStruct::id, taskStruct::last_exit, sys_wait4_args::pid, sched_setStatus(), sched_yield(), schedFindTask(), thread::td_retval, and WAIT.