UbixOS V2: C:/Dev/git/UbixOS/sys/include/pci/hd.h File Reference
hd.h File Reference
#include <sys/types.h>
#include <ubixfs/ubixfs.h>
Data Structures
struct ata_identify_data
struct bsd_disklabel
struct bsd_disklabel::partition
struct dos_partition
struct driveInfo
Macros
#define ATA_A_4BIT 0x00
#define ATA_A_HOB 0x80 /* High Order Byte enable */
#define ATA_A_IDS 0x02 /* disable interrupts */
#define ATA_A_RESET 0x04 /* RESET controller */
#define ATA_ALTSTAT 11 /* (R) alternate status */
#define ATA_CHECK_POWER_MODE 0xE5
#define ATA_COMMAND 7 /* (W) command */
#define ATA_CONTROL 12 /* (W) control */
#define ATA_COUNT 2 /* (W) sector count */
#define ATA_CTLOFFSET 0x206 /* control register offset */
#define ATA_CYL_LSB 4 /* (RW) cylinder# LSB */
#define ATA_CYL_MSB 5 /* (RW) cylinder# MSB */
#define ATA_D_IBM 0xa0 /* 512 byte sectors, ECC */
#define ATA_D_LBA 0x40 /* use LBA addressing */
#define ATA_DATA 0 /* (RW) data */
#define ATA_DATA_SET_MANAGEMENT 0x06
#define ATA_DEVICE_RESET 0x08
#define ATA_DOWNLOAD_MICROCODE 0x92
#define ATA_DRIVE 6 /* (W) Sector/Drive/Head */
#define ATA_E_ABORT 0x04 /* command aborted */
#define ATA_E_ATAPI_SENSE_MASK 0xf0 /* ATAPI sense key mask */
#define ATA_E_ICRC 0x80 /* UDMA crc error */
#define ATA_E_IDNF 0x10 /* ID not found */
#define ATA_E_ILI 0x01 /* illegal length */
#define ATA_E_MC 0x20 /* media changed */
#define ATA_E_MCR 0x08 /* media change request */
#define ATA_E_NM 0x02 /* no media */
#define ATA_E_UNC 0x40 /* uncorrectable data */
#define ATA_ERROR 8 /* (R) error */
#define ATA_EXECUTE_DEVICE_DIAG 0x90
#define ATA_F_DMA 0x01 /* enable DMA */
#define ATA_F_OVL 0x02 /* enable overlap */
#define ATA_FEATURE 1 /* (W) feature */
#define ATA_FLUSH_CACHE 0xE7
#define ATA_FLUSH_CACHE_EXT 0xEA
#define ATA_I_CMD 0x01 /* cmd (1) | data (0) */
#define ATA_I_IN 0x02 /* read (1) | write (0) */
#define ATA_I_RELEASE 0x04 /* released bus (1) */
#define ATA_I_TAGMASK 0xf8 /* tag mask */
#define ATA_IDENTIFY 0xEC
#define ATA_IDENTIFY_COMMAND_SET_SUPPORTED1_48BIT_ENABLE 0x0400
#define ATA_IDENTIFY_SECTOR_LARGER_THEN_512_ENABLE 0x0100
#define ATA_IDLE 0xE3
#define ATA_IDLE_IMMED 0xE1
#define ATA_IREASON 9 /* (R) interrupt reason */
#define ATA_MEDIA_EJECT 0xED
#define ATA_NOP 0x00
#define ATA_PACKET 0xA0
#define ATA_PACKET_IDENTIFY 0xA1
#define ATA_PC98_CTLOFFSET 0x10c /* do for PC98 devices */
#define ATA_PCCARD_CTLOFFSET 0x0e /* do for PCCARD devices */
#define ATA_READ_BUFFER 0xE4
#define ATA_READ_DMA 0xC8
#define ATA_READ_DMA_EXT 0x25
#define ATA_READ_DMA_QUEUED 0xC7
#define ATA_READ_DMA_QUEUED_EXT 0x26
#define ATA_READ_FPDMA 0x60
#define ATA_READ_LOG_DMA_EXT 0x47
#define ATA_READ_LOG_EXT 0x2F
#define ATA_READ_MULTIPLE 0xC4
#define ATA_READ_MULTIPLE_EXT 0x29
#define ATA_READ_SECTORS 0x20
#define ATA_READ_SECTORS_EXT 0x24
#define ATA_READ_STREAM_DMA_EXT 0x2A
#define ATA_READ_VERIFY_SECTORS 0x40
#define ATA_READ_VERIFY_SECTORS_EXT 0x42
#define ATA_S_BUSY 0x80 /* busy */
#define ATA_S_CORR 0x04 /* data corrected */
#define ATA_S_DMA 0x20 /* DMA ready */
#define ATA_S_DRQ 0x08 /* data request */
#define ATA_S_DSC 0x10 /* drive seek completed */
#define ATA_S_DWF 0x20 /* drive write fault */
#define ATA_S_ERROR 0x01 /* error */
#define ATA_S_INDEX 0x02 /* index */
#define ATA_S_READY 0x40 /* drive ready */
#define ATA_S_SERVICE 0x10 /* drive needs service */
#define ATA_SECTOR 3 /* (RW) sector # */
#define ATA_SECURITY_FREEZE_LOCK 0xF5
#define ATA_SECURITY_UNLOCK 0xF2
#define ATA_SET_FEATURES 0xEF
#define ATA_SMART 0xB0
#define ATA_STANDBY 0xE2
#define ATA_STANDBY_IMMED 0xE0
#define ATA_STATUS 10 /* (R) status */
#define ATA_WRITE_BUFFER 0xE8
#define ATA_WRITE_DMA 0xCA
#define ATA_WRITE_DMA_EXT 0x35
#define ATA_WRITE_DMA_FUA 0x3D
#define ATA_WRITE_DMA_QUEUED 0xCC
#define ATA_WRITE_DMA_QUEUED_EXT 0x36
#define ATA_WRITE_DMA_QUEUED_FUA_EXT 0x3E
#define ATA_WRITE_FPDMA 0x61
#define ATA_WRITE_LOG_DMA_EXT 0x57
#define ATA_WRITE_MULTIPLE 0xC5
#define ATA_WRITE_MULTIPLE_EXT 0x39
#define ATA_WRITE_MULTIPLE_FUA_EXT 0xCE
#define ATA_WRITE_SECTORS 0x30
#define ATA_WRITE_SECTORS_EXT 0x34
#define ATA_WRITE_STREAM_DMA_EXT 0x3A
#define ATA_WRITE_UNCORRECTABLE 0x45
#define hdCmd 0x7
#define hdCylHi 0x5
#define hdCylLow 0x4
#define hdData 0x0
#define hdError 0x1
#define hdHead 0x6
#define hdSecCount 0x2
#define hdSecNum 0x3
#define hdStat 0x7
#define MAXPARTITIONS 8
#define NDDATA 5
#define NSPARE 5
Functions
int hdInit (struct device_node *dev)
int hdIoctl ()
int hdRead (struct driveInfo *hdd, void *, uInt32, uInt32)
int hdReset ()
int hdStandby ()
int hdStart ()
int hdStop ()
int hdWrite (struct driveInfo *hdd, void *, uInt32, uInt32)
int initHardDisk ()
ATA_IDENTIFY_DEVICE_FIELD_LENGTHS
The following constants define the number of bytes contained in various fields found in the IDENTIFY DEVICE data structure.
#define ATA_IDENTIFY_48_LBA_LEN 8
#define ATA_IDENTIFY_FW_REVISION_LEN 8
#define ATA_IDENTIFY_MEDIA_SERIAL_NUMBER_LEN 30
#define ATA_IDENTIFY_MODEL_NUMBER_LEN 40
#define ATA_IDENTIFY_SERIAL_NUMBER_LEN 20
#define ATA_IDENTIFY_WWN_LEN 8
Macro Definition Documentation
ATA_A_4BIT
#define ATA_A_4BIT 0x00
Definition at line 107 of file hd.h.
ATA_A_HOB
#define ATA_A_HOB 0x80 /* High Order Byte enable */
Definition at line 109 of file hd.h.
ATA_A_IDS
#define ATA_A_IDS 0x02 /* disable interrupts */
Definition at line 102 of file hd.h.
ATA_A_RESET
#define ATA_A_RESET 0x04 /* RESET controller */
Definition at line 103 of file hd.h.
ATA_ALTSTAT
#define ATA_ALTSTAT 11 /* (R) alternate status */
Definition at line 85 of file hd.h.
ATA_CHECK_POWER_MODE
#define ATA_CHECK_POWER_MODE 0xE5
Definition at line 113 of file hd.h.
ATA_COMMAND
#define ATA_COMMAND 7 /* (W) command */
Definition at line 65 of file hd.h.
ATA_CONTROL
#define ATA_CONTROL 12 /* (W) control */
Definition at line 97 of file hd.h.
ATA_COUNT
#define ATA_COUNT 2 /* (W) sector count */
Definition at line 56 of file hd.h.
ATA_CTLOFFSET
#define ATA_CTLOFFSET 0x206 /* control register offset */
Definition at line 99 of file hd.h.
ATA_CYL_LSB
#define ATA_CYL_LSB 4 /* (RW) cylinder# LSB */
Definition at line 59 of file hd.h.
ATA_CYL_MSB
#define ATA_CYL_MSB 5 /* (RW) cylinder# MSB */
Definition at line 60 of file hd.h.
ATA_D_IBM
#define ATA_D_IBM 0xa0 /* 512 byte sectors, ECC */
Definition at line 63 of file hd.h.
ATA_D_LBA
#define ATA_D_LBA 0x40 /* use LBA addressing */
Definition at line 62 of file hd.h.
ATA_DATA
#define ATA_DATA 0 /* (RW) data */
Definition at line 50 of file hd.h.
ATA_DATA_SET_MANAGEMENT
#define ATA_DATA_SET_MANAGEMENT 0x06
Definition at line 146 of file hd.h.
ATA_DEVICE_RESET
#define ATA_DEVICE_RESET 0x08
Definition at line 142 of file hd.h.
ATA_DOWNLOAD_MICROCODE
#define ATA_DOWNLOAD_MICROCODE 0x92
Definition at line 147 of file hd.h.
ATA_DRIVE
#define ATA_DRIVE 6 /* (W) Sector/Drive/Head */
Definition at line 61 of file hd.h.
ATA_E_ABORT
#define ATA_E_ABORT 0x04 /* command aborted */
Definition at line 70 of file hd.h.
ATA_E_ATAPI_SENSE_MASK
#define ATA_E_ATAPI_SENSE_MASK 0xf0 /* ATAPI sense key mask */
Definition at line 76 of file hd.h.
ATA_E_ICRC
#define ATA_E_ICRC 0x80 /* UDMA crc error */
Definition at line 75 of file hd.h.
ATA_E_IDNF
#define ATA_E_IDNF 0x10 /* ID not found */
Definition at line 72 of file hd.h.
ATA_E_ILI
#define ATA_E_ILI 0x01 /* illegal length */
Definition at line 68 of file hd.h.
ATA_E_MC
#define ATA_E_MC 0x20 /* media changed */
Definition at line 73 of file hd.h.
ATA_E_MCR
#define ATA_E_MCR 0x08 /* media change request */
Definition at line 71 of file hd.h.
ATA_E_NM
#define ATA_E_NM 0x02 /* no media */
Definition at line 69 of file hd.h.
ATA_E_UNC
#define ATA_E_UNC 0x40 /* uncorrectable data */
Definition at line 74 of file hd.h.
ATA_ERROR
#define ATA_ERROR 8 /* (R) error */
Definition at line 67 of file hd.h.
ATA_EXECUTE_DEVICE_DIAG
#define ATA_EXECUTE_DEVICE_DIAG 0x90
Definition at line 133 of file hd.h.
ATA_F_DMA
#define ATA_F_DMA 0x01 /* enable DMA */
Definition at line 53 of file hd.h.
ATA_F_OVL
#define ATA_F_OVL 0x02 /* enable overlap */
Definition at line 54 of file hd.h.
ATA_FEATURE
#define ATA_FEATURE 1 /* (W) feature */
Definition at line 52 of file hd.h.
ATA_FLUSH_CACHE
#define ATA_FLUSH_CACHE 0xE7
Definition at line 118 of file hd.h.
ATA_FLUSH_CACHE_EXT
#define ATA_FLUSH_CACHE_EXT 0xEA
Definition at line 119 of file hd.h.
ATA_I_CMD
#define ATA_I_CMD 0x01 /* cmd (1) | data (0) */
Definition at line 79 of file hd.h.
ATA_I_IN
#define ATA_I_IN 0x02 /* read (1) | write (0) */
Definition at line 80 of file hd.h.
ATA_I_RELEASE
#define ATA_I_RELEASE 0x04 /* released bus (1) */
Definition at line 81 of file hd.h.
ATA_I_TAGMASK
#define ATA_I_TAGMASK 0xf8 /* tag mask */
Definition at line 82 of file hd.h.
ATA_IDENTIFY
#define ATA_IDENTIFY 0xEC
Definition at line 112 of file hd.h.
ATA_IDENTIFY_48_LBA_LEN
#define ATA_IDENTIFY_48_LBA_LEN 8
Definition at line 296 of file hd.h.
ATA_IDENTIFY_COMMAND_SET_SUPPORTED1_48BIT_ENABLE
#define ATA_IDENTIFY_COMMAND_SET_SUPPORTED1_48BIT_ENABLE 0x0400
Definition at line 46 of file hd.h.
ATA_IDENTIFY_FW_REVISION_LEN
#define ATA_IDENTIFY_FW_REVISION_LEN 8
Definition at line 295 of file hd.h.
ATA_IDENTIFY_MEDIA_SERIAL_NUMBER_LEN
#define ATA_IDENTIFY_MEDIA_SERIAL_NUMBER_LEN 30
Definition at line 297 of file hd.h.
ATA_IDENTIFY_MODEL_NUMBER_LEN
#define ATA_IDENTIFY_MODEL_NUMBER_LEN 40
Definition at line 294 of file hd.h.
ATA_IDENTIFY_SECTOR_LARGER_THEN_512_ENABLE
#define ATA_IDENTIFY_SECTOR_LARGER_THEN_512_ENABLE 0x0100
Definition at line 47 of file hd.h.
ATA_IDENTIFY_SERIAL_NUMBER_LEN
#define ATA_IDENTIFY_SERIAL_NUMBER_LEN 20
Definition at line 293 of file hd.h.
ATA_IDENTIFY_WWN_LEN
#define ATA_IDENTIFY_WWN_LEN 8
Definition at line 298 of file hd.h.
ATA_IDLE
#define ATA_IDLE 0xE3
Definition at line 117 of file hd.h.
ATA_IDLE_IMMED
#define ATA_IDLE_IMMED 0xE1
Definition at line 116 of file hd.h.
ATA_IREASON
#define ATA_IREASON 9 /* (R) interrupt reason */
Definition at line 78 of file hd.h.
ATA_MEDIA_EJECT
#define ATA_MEDIA_EJECT 0xED
Definition at line 143 of file hd.h.
ATA_NOP
#define ATA_NOP 0x00
Definition at line 141 of file hd.h.
ATA_PACKET
#define ATA_PACKET 0xA0
Definition at line 137 of file hd.h.
ATA_PACKET_IDENTIFY
#define ATA_PACKET_IDENTIFY 0xA1
Definition at line 136 of file hd.h.
ATA_PC98_CTLOFFSET
#define ATA_PC98_CTLOFFSET 0x10c /* do for PC98 devices */
Definition at line 101 of file hd.h.
ATA_PCCARD_CTLOFFSET
#define ATA_PCCARD_CTLOFFSET 0x0e /* do for PCCARD devices */
Definition at line 100 of file hd.h.
ATA_READ_BUFFER
#define ATA_READ_BUFFER 0xE4
Definition at line 131 of file hd.h.
ATA_READ_DMA
#define ATA_READ_DMA 0xC8
Definition at line 121 of file hd.h.
ATA_READ_DMA_EXT
#define ATA_READ_DMA_EXT 0x25
Definition at line 120 of file hd.h.
ATA_READ_DMA_QUEUED
#define ATA_READ_DMA_QUEUED 0xC7
Definition at line 153 of file hd.h.
ATA_READ_DMA_QUEUED_EXT
#define ATA_READ_DMA_QUEUED_EXT 0x26
Definition at line 154 of file hd.h.
ATA_READ_FPDMA
#define ATA_READ_FPDMA 0x60
Definition at line 138 of file hd.h.
ATA_READ_LOG_DMA_EXT
#define ATA_READ_LOG_DMA_EXT 0x47
Definition at line 149 of file hd.h.
ATA_READ_LOG_EXT
#define ATA_READ_LOG_EXT 0x2F
Definition at line 140 of file hd.h.
ATA_READ_MULTIPLE
#define ATA_READ_MULTIPLE 0xC4
Definition at line 158 of file hd.h.
ATA_READ_MULTIPLE_EXT
#define ATA_READ_MULTIPLE_EXT 0x29
Definition at line 159 of file hd.h.
ATA_READ_SECTORS
#define ATA_READ_SECTORS 0x20
Definition at line 123 of file hd.h.
ATA_READ_SECTORS_EXT
#define ATA_READ_SECTORS_EXT 0x24
Definition at line 122 of file hd.h.
ATA_READ_STREAM_DMA_EXT
#define ATA_READ_STREAM_DMA_EXT 0x2A
Definition at line 150 of file hd.h.
ATA_READ_VERIFY_SECTORS
#define ATA_READ_VERIFY_SECTORS 0x40
Definition at line 129 of file hd.h.
ATA_READ_VERIFY_SECTORS_EXT
#define ATA_READ_VERIFY_SECTORS_EXT 0x42
Definition at line 130 of file hd.h.
ATA_S_BUSY
#define ATA_S_BUSY 0x80 /* busy */
Definition at line 95 of file hd.h.
ATA_S_CORR
#define ATA_S_CORR 0x04 /* data corrected */
Definition at line 88 of file hd.h.
ATA_S_DMA
#define ATA_S_DMA 0x20 /* DMA ready */
Definition at line 93 of file hd.h.
ATA_S_DRQ
#define ATA_S_DRQ 0x08 /* data request */
Definition at line 89 of file hd.h.
ATA_S_DSC
#define ATA_S_DSC 0x10 /* drive seek completed */
Definition at line 90 of file hd.h.
ATA_S_DWF
#define ATA_S_DWF 0x20 /* drive write fault */
Definition at line 92 of file hd.h.
ATA_S_ERROR
#define ATA_S_ERROR 0x01 /* error */
Definition at line 86 of file hd.h.
ATA_S_INDEX
#define ATA_S_INDEX 0x02 /* index */
Definition at line 87 of file hd.h.
ATA_S_READY
#define ATA_S_READY 0x40 /* drive ready */
Definition at line 94 of file hd.h.
ATA_S_SERVICE
#define ATA_S_SERVICE 0x10 /* drive needs service */
Definition at line 91 of file hd.h.
ATA_SECTOR
#define ATA_SECTOR 3 /* (RW) sector # */
Definition at line 58 of file hd.h.
ATA_SECURITY_FREEZE_LOCK
#define ATA_SECURITY_FREEZE_LOCK 0xF5
Definition at line 145 of file hd.h.
ATA_SECURITY_UNLOCK
#define ATA_SECURITY_UNLOCK 0xF2
Definition at line 144 of file hd.h.
ATA_SET_FEATURES
#define ATA_SET_FEATURES 0xEF
Definition at line 134 of file hd.h.
ATA_SMART
#define ATA_SMART 0xB0
Definition at line 135 of file hd.h.
ATA_STANDBY
#define ATA_STANDBY 0xE2
Definition at line 114 of file hd.h.
ATA_STANDBY_IMMED
#define ATA_STANDBY_IMMED 0xE0
Definition at line 115 of file hd.h.
ATA_STATUS
#define ATA_STATUS 10 /* (R) status */
Definition at line 84 of file hd.h.
ATA_WRITE_BUFFER
#define ATA_WRITE_BUFFER 0xE8
Definition at line 132 of file hd.h.
ATA_WRITE_DMA
#define ATA_WRITE_DMA 0xCA
Definition at line 125 of file hd.h.
ATA_WRITE_DMA_EXT
#define ATA_WRITE_DMA_EXT 0x35
Definition at line 124 of file hd.h.
ATA_WRITE_DMA_FUA
#define ATA_WRITE_DMA_FUA 0x3D
Definition at line 151 of file hd.h.
ATA_WRITE_DMA_QUEUED
#define ATA_WRITE_DMA_QUEUED 0xCC
Definition at line 155 of file hd.h.
ATA_WRITE_DMA_QUEUED_EXT
#define ATA_WRITE_DMA_QUEUED_EXT 0x36
Definition at line 156 of file hd.h.
ATA_WRITE_DMA_QUEUED_FUA_EXT
#define ATA_WRITE_DMA_QUEUED_FUA_EXT 0x3E
Definition at line 157 of file hd.h.
ATA_WRITE_FPDMA
#define ATA_WRITE_FPDMA 0x61
Definition at line 139 of file hd.h.
ATA_WRITE_LOG_DMA_EXT
#define ATA_WRITE_LOG_DMA_EXT 0x57
Definition at line 152 of file hd.h.
ATA_WRITE_MULTIPLE
#define ATA_WRITE_MULTIPLE 0xC5
Definition at line 160 of file hd.h.
ATA_WRITE_MULTIPLE_EXT
#define ATA_WRITE_MULTIPLE_EXT 0x39
Definition at line 161 of file hd.h.
ATA_WRITE_MULTIPLE_FUA_EXT
#define ATA_WRITE_MULTIPLE_FUA_EXT 0xCE
Definition at line 162 of file hd.h.
ATA_WRITE_SECTORS
#define ATA_WRITE_SECTORS 0x30
Definition at line 127 of file hd.h.
ATA_WRITE_SECTORS_EXT
#define ATA_WRITE_SECTORS_EXT 0x34
Definition at line 126 of file hd.h.
ATA_WRITE_STREAM_DMA_EXT
#define ATA_WRITE_STREAM_DMA_EXT 0x3A
Definition at line 148 of file hd.h.
ATA_WRITE_UNCORRECTABLE
#define ATA_WRITE_UNCORRECTABLE 0x45
Definition at line 128 of file hd.h.
hdCmd
#define hdCmd 0x7
Definition at line 43 of file hd.h.
hdCylHi
#define hdCylHi 0x5
Definition at line 40 of file hd.h.
hdCylLow
#define hdCylLow 0x4
Definition at line 39 of file hd.h.
hdData
#define hdData 0x0
Definition at line 35 of file hd.h.
hdError
#define hdError 0x1
Definition at line 36 of file hd.h.
hdHead
#define hdHead 0x6
Definition at line 41 of file hd.h.
hdSecCount
#define hdSecCount 0x2
Definition at line 37 of file hd.h.
hdSecNum
#define hdSecNum 0x3
Definition at line 38 of file hd.h.
hdStat
#define hdStat 0x7
Definition at line 42 of file hd.h.
MAXPARTITIONS
#define MAXPARTITIONS 8
Definition at line 208 of file hd.h.
NDDATA
#define NDDATA 5
Definition at line 264 of file hd.h.
NSPARE
#define NSPARE 5
Definition at line 266 of file hd.h.
Function Documentation
hdInit()
int hdInit (struct device_node * dev)
Definition at line 221 of file hd.c.
References ATA_COMMAND, ATA_DATA, ATA_DRIVE, ATA_IDENTIFY, driveInfo::ata_identify, ATA_IDENTIFY_COMMAND_SET_SUPPORTED1_48BIT_ENABLE, ATA_IDENTIFY_SECTOR_LARGER_THEN_512_ENABLE, ATA_S_BUSY, ata_identify_data::command_set_enabled1, device_node::devInfo, hdCmd, driveInfo::hdDev, driveInfo::hdEnable, hdHead, driveInfo::hdMask, driveInfo::hdMulti, driveInfo::hdPort, hdSecCount, driveInfo::hdShift, driveInfo::hdSize, device_interface::info, device_interface::initialized, inportByte(), inportWord(), kprintf(), driveInfo::lba_high, driveInfo::lba_low, ata_identify_data::max_48bit_lba, outportByte(), ata_identify_data::physical_logical_sector_info, driveInfo::sector_size, device_interface::size, ata_identify_data::total_num_sectors, and ata_identify_data::words_per_logical_sector.
hdIoctl()
int hdIoctl ()
Definition at line 211 of file hd.c.
hdRead()
int hdRead (struct driveInfo * hdd, void * , uInt32 , uInt32)
Definition at line 423 of file hd.c.
References driveInfo::hdCalc, hdCmd, hdCylHi, hdCylLow, hdData, driveInfo::hdDev, driveInfo::hdEnable, hdHead, driveInfo::hdMulti, driveInfo::hdPort, hdSecCount, hdSecNum, driveInfo::hdShift, hdStat, inportByte(), inportWord(), kprintf(), driveInfo::lba_start, outportByte(), and driveInfo::parOffset.
hdReset()
int hdReset ()
Definition at line 216 of file hd.c.
hdStandby()
int hdStandby ()
Definition at line 196 of file hd.c.
hdStart()
int hdStart ()
Definition at line 201 of file hd.c.
hdStop()
int hdStop ()
Definition at line 206 of file hd.c.
hdWrite()
int hdWrite (struct driveInfo * hdd, void * , uInt32 , uInt32)
Definition at line 356 of file hd.c.
References driveInfo::hdCalc, hdCmd, hdCylHi, hdCylLow, hdData, driveInfo::hdDev, driveInfo::hdEnable, hdHead, driveInfo::hdMulti, driveInfo::hdPort, hdSecCount, hdSecNum, driveInfo::hdShift, hdStat, inportByte(), kprintf(), driveInfo::lba_start, outportByte(), outportWord(), and driveInfo::parOffset.
initHardDisk()
int initHardDisk ()
Definition at line 42 of file hd.c.
References _initHardDisk().