UbixOS V2: C:/Dev/git/UbixOS/sys/include/sys/device.h File Reference
device.h File Reference
#include <sys/types.h>
Data Structures
struct device_interface
struct device_node
struct device_resource
Functions
int device_add (int, char, struct device_interface *)
struct device_node * device_find (int major, int minor)
int device_remove (struct device_node *)
Function Documentation
device_add()
int device_add (int , char , struct device_interface *)
Definition at line 49 of file device.c.
References device_node::devInfo, kmalloc(), kprintf(), device_node::minor, NULL, device_node::prev, spinLock(), and device_node::type.
Referenced by fdc_init().
device_find()
struct device_node* device_find (int major, int minor)
Definition at line 82 of file device.c.
References spinLock().
Referenced by vfs_mount().
device_remove()
int device_remove (struct device_node *)
Definition at line 104 of file device.c.