UbixOS V2: C:/Dev/git/UbixOS/sys/kernel/syscall.c File Reference
syscall.c File Reference
#include <ubixos/syscalls.h>
#include <ubixos/syscall.h>
#include <ubixos/sched.h>
#include <ubixos/endtask.h>
#include <ubixos/spinlock.h>
#include <ubixos/vitals.h>
#include <sys/trap.h>
#include <sys/elf.h>
#include <string.h>
#include <lib/kprintf.h>
#include <ubixos/kpanic.h>
#include <vmm/vmm.h>
Data Structures
struct _UbixUser
Typedefs
typedef struct _UbixUser UbixUser
Functions
int invalidCall ()
void sys_call (struct trapframe *frame)
int sys_getcwd (struct thread *td, struct sys_getcwd_args *args)
int sys_sched_yield (struct thread *td, void *args)
int sysAddModule ()
int sysAuth (UbixUser *uu)
int sysCheckPid (int pid, int *ptr)
int sysExit (int status)
int sysGetDrives (uInt32 *ptr)
int sysGetFreePage (struct thread *td, uint32_t *count)
int sysGetpid (int *pid)
int sysGetTime (uInt32 *ptr)
int sysGetUptime (uInt32 *ptr)
int sysPasswd (char *passwd)
int sysRmModule ()
int sysStartSDE ()
Typedef Documentation
UbixUser
typedef struct _UbixUser UbixUser
Definition at line 115 of file syscall.c.
Function Documentation
invalidCall()
int invalidCall ()
Definition at line 101 of file syscall.c.
References _current, taskStruct::id, kprintf(), and sys_call().
sys_call()
void sys_call (struct trapframe * frame)
Definition at line 43 of file syscall.c.
References _current, thread::abi, die_if_kernel(), ELFOSABI_FREEBSD, thread::frame, taskStruct::id, kpanic(), kprintf(), PSL_C, syscall_entry::sc_name, SYSCALL_DUMMY, SYSCALL_INVALID, systemCalls, taskStruct::td, thread::td_retval, trapframe::tf_eax, trapframe::tf_edx, trapframe::tf_eflags, trapframe::tf_esp, and totalCalls.
Referenced by invalidCall(), and invalidCall_posix().
sys_getcwd()
int sys_getcwd (struct thread * td, struct sys_getcwd_args * args)
Definition at line 204 of file syscall.c.
References _current, sys_getcwd_args::buf, osInfo::cwd, taskStruct::oInfo, sprintf(), and strlen().
sys_sched_yield()
int sys_sched_yield (struct thread * td, void * args)
Definition at line 224 of file syscall.c.
References sched_yield().
sysAddModule()
int sysAddModule ()
Definition at line 145 of file syscall.c.
sysAuth()
int sysAuth (UbixUser * uu)
Definition at line 125 of file syscall.c.
References kprintf().
sysCheckPid()
int sysCheckPid (int pid, int * ptr)
Definition at line 164 of file syscall.c.
References schedFindTask(), and taskStruct::state.
sysExit()
int sysExit (int status)
Definition at line 159 of file syscall.c.
sysGetDrives()
int sysGetDrives (uInt32 * ptr)
Definition at line 186 of file syscall.c.
sysGetFreePage()
int sysGetFreePage (struct thread * td, uint32_t * count)
Definition at line 179 of file syscall.c.
References _current, taskStruct::id, thread::td_retval, VM_THRD, and vmm_getFreeVirtualPage().
sysGetpid()
int sysGetpid (int * pid)
Definition at line 153 of file syscall.c.
References _current, and taskStruct::id.
sysGetTime()
int sysGetTime (uInt32 * ptr)
Definition at line 198 of file syscall.c.
References systemVitals, vitalsStruct::sysUptime, and vitalsStruct::timeStart.
sysGetUptime()
int sysGetUptime (uInt32 * ptr)
Definition at line 192 of file syscall.c.
References systemVitals, and vitalsStruct::sysTicks.
sysPasswd()
int sysPasswd (char * passwd)
Definition at line 140 of file syscall.c.
References _current, kprintf(), and taskStruct::uid.
sysRmModule()
int sysRmModule ()
Definition at line 149 of file syscall.c.
sysStartSDE()
int sysStartSDE ()
Definition at line 229 of file syscall.c.