UbixOS V2: C:/Dev/git/UbixOS/sys/include/ubixos/kmod.h File Reference
kmod.h File Reference
#include <sys/types.h>
Data Structures
struct kmod_struct
Macros
#define LD_START 0x1000000
Typedefs
typedef struct kmod_struct kmod_t
Functions
uInt32 kmod_add (const char *, const char *name)
uInt32 kmod_load (const char *)
Macro Definition Documentation
LD_START
#define LD_START 0x1000000
Definition at line 34 of file kmod.h.
Typedef Documentation
kmod_t
typedef struct kmod_struct kmod_t
Function Documentation
kmod_add()
uInt32 kmod_add (const char * , const char * name)
Definition at line 45 of file kmod.c.
References CreateItem(), _item_t::data, InitializeList(), InsertItemAtFront(), kmalloc(), kmod_load(), kprintf(), List, and NULL.
kmod_load()
uInt32 kmod_load (const char *)
Definition at line 70 of file kmod.c.
References _current, assert, ELF32_R_SYM, ELF32_R_TYPE, elfGetRelType(), fclose(), fopen(), fread(), fseek(), taskStruct::id, kfree(), kmalloc(), kpanic(), kprintf(), LD_START, memset(), PAGE_DEFAULT, PT_DYNAMIC, PT_GNU_STACK, PT_LOAD, R_386_32, R_386_PC32, R_386_RELATIVE, strcmp(), vmm_findFreePage(), and vmm_remapPage().
Referenced by kmod_add().