UbixOS V2: C:/Dev/git/UbixOS/sys/kernel/ld.c File Reference
ld.c File Reference
#include <ubixos/ld.h>
#include <ubixos/sched.h>
#include <sys/elf.h>
#include <ubixos/kpanic.h>
#include <lib/kprintf.h>
#include <lib/kmalloc.h>
#include <vfs/vfs.h>
#include <vmm/vmm.h>
#include <string.h>
#include <assert.h>
Functions
uint32_t ldEnable (const char *interp)
Function Documentation
ldEnable()
uint32_t ldEnable (const char * interp)
Definition at line 40 of file ld.c.
References _current, assert, ELF32_R_SYM, ELF32_R_TYPE, elfGetRelType(), fclose(), fopen(), fread(), fseek(), taskStruct::id, K_PANIC, kfree(), kmalloc(), kprintf(), LD_START, memset(), PAGE_DEFAULT, PT_DYNAMIC, PT_GNU_STACK, PT_LOAD, R_386_32, R_386_NONE, R_386_PC32, R_386_RELATIVE, SHT_DYNAMIC, SHT_DYNSYM, SHT_HASH, SHT_PROGBITS, SHT_REL, SHT_STRTAB, SHT_SYMTAB, strcmp(), vmm_findFreePage(), and vmm_remapPage().