UbixOS V2: C:/Dev/git/UbixOS/sys/lib/libcpp.cc File Reference
libcpp.cc File Reference
#include <lib/kmalloc.h>
#include <sys/video.h>
#include <lib/libcpp.h>
Functions
int __cxa_atexit (void(*func)(void *), void *arg, void *d)
void __cxa_pure_virtual ()
void __dso_handle ()
void __pure_virtual ()
void operator delete (void *ptr)
void operator delete[] (void *ptr)
void * operator new (unsigned size)
void * operator new[] (unsigned size)
Function Documentation
__cxa_atexit()
int __cxa_atexit (void(*)(void *) func, void * arg, void * d)
Definition at line 45 of file libcpp.cc.
__cxa_pure_virtual()
void __cxa_pure_virtual ()
Definition at line 39 of file libcpp.cc.
__dso_handle()
void __dso_handle ()
Definition at line 49 of file libcpp.cc.
__pure_virtual()
void __pure_virtual ()
Definition at line 34 of file libcpp.cc.
operator delete()
void operator delete (void * ptr)
Definition at line 73 of file libcpp.cc.
References kfree().
operator delete[]()
void operator delete[] (void * ptr)
Definition at line 62 of file libcpp.cc.
References kfree().
operator new()
void* operator new (unsigned size)
Definition at line 68 of file libcpp.cc.
References kmalloc().
operator new[]()
void* operator new[] (unsigned size)
Definition at line 58 of file libcpp.cc.
References kmalloc().