UbixOS V2: C:/Dev/git/UbixOS/sys/sde/main.cc File Reference
main.cc File Reference
#include <lib/kprintf.h>
#include <ubixos/vitals.h>
#include <ubixos/exec.h>
#include <vmm/vmm.h>
#include <lib/kmalloc.h>
#include <sde/sde.h>
#include <objgfx40/objgfx40.h>
#include <sde/ogDisplay_UbixOS.h>
#include <objgfx40/ogFont.h>
Functions
void sdeTestThread ()
void sdeThread ()
Function Documentation
sdeTestThread()
void sdeTestThread ()
Definition at line 42 of file colours.cc.
References sched_yield(), vitalsStruct::screen, and systemVitals.
Referenced by sdeThread().
sdeThread()
void sdeThread ()
Definition at line 51 of file main.cc.
References sdeWindows::buf, drawWindow, execThread(), vitalsStruct::font, kfree(), killWindow, kprintf(), sdeWindows::next, ogprintOff, sdeWindows::pid, sdeWindows::prev, printOff, registerWindow, sched_yield(), vitalsStruct::screen, sdeTestThread(), sdeWindows::status, systemVitals, VMM_KEEP, vmm_mapFromTask(), vmm_unmapPages(), windowReady, and windows.
Referenced by systemTask().