UbixOS V2: C:/Dev/git/UbixOS/sys/fs/vfs/namei.c File Reference
namei.c File Reference
#include <sys/types.h>
#include <ubixos/errno.h>
#include <vfs/vfs.h>
#include <ubixos/sched.h>
Functions
int follow_link (struct inode *dir, struct inode *inode, int flag, int mode, struct inode **res_inode)
int lookup (struct inode *dir, const char *name, int len, struct inode **result)
int namei (const char *pathname, struct inode *base, int follow_links, struct inode **res_inode)
int permission (struct inode *inode, int mask)
Function Documentation
follow_link()
int follow_link (struct inode * dir, struct inode * inode, int flag, int mode, struct inode ** res_inode)
Definition at line 34 of file namei.c.
References ENOENT, inode_operations::follow_link, inode::i_op, iput(), and NULL.
lookup()
int lookup (struct inode * dir, const char * name, int len, struct inode ** result)
Definition at line 68 of file namei.c.
References _current, EACCES, ENOENT, ENOTDIR, inode::i_count, inode::i_op, inode::i_sb, iput(), inode_operations::lookup, MAY_EXEC, name, NULL, permission(), taskStruct::root, super_block::s_covered, and super_block::s_mounted.
namei()
int namei (const char * pathname, struct inode * base, int follow_links, struct inode ** res_inode)
Definition at line 172 of file namei.c.
References NULL.
permission()
int permission (struct inode * inode, int mask)
Definition at line 52 of file namei.c.
References _current, taskStruct::euid, inode::i_gid, inode::i_mode, inode::i_op, inode::i_uid, in_group_p(), and inode_operations::permission.
Referenced by lookup().