UbixOS V2: C:/Dev/git/UbixOS/sys/net/net/init.c File Reference
init.c File Reference
#include <sys/types.h>
#include <ubixos/sched.h>
#include <ubixos/endtask.h>
#include <ubixos/sem.h>
#include <net/sys.h>
#include <net/mem.h>
#include <net/memp.h>
#include <net/tcpip.h>
#include <net/ip_addr.h>
#include <netif/ethernet.h>
#include <netif/ethernetif.h>
#include <ubixos/exec.h>
#include <lib/kmalloc.h>
#include <lib/kprintf.h>
Functions
void lnc_thread ()
int net_init ()
void shell_thread (void *)
Variables
struct netif lnc_netif
Function Documentation
lnc_thread()
void lnc_thread ()
Definition at line 278 of file lnc.c.
References nicBuffer::buffer, lncInfo::bufferSize, ethernetif_input(), kmalloc(), nicBuffer::length, lnc, lnc_driverOwnsRX(), lnc_netif, lnc_nextRxPtr(), hostRingEntry::md, memset(), lncInfo::rxBuffer, lncInfo::rxPtr, lncInfo::rxRing, sched_yield(), and tmpBuf.
Referenced by net_init().
net_init()
int net_init ()
Definition at line 52 of file init.c.
References ethernetif_init(), lnc_netif, lnc_thread(), netif_add(), netif_set_default(), netif_set_link_up(), netif_set_up(), NULL, shell_thread(), sys_thread_new(), tcpip_init(), and tcpip_input().
shell_thread()
void shell_thread (void *)
Definition at line 95 of file shell.c.
References buffer, and kmalloc().
Referenced by net_init().
Variable Documentation
lnc_netif
struct netif lnc_netif
Definition at line 50 of file init.c.
Referenced by net_init().