UbixOS V2: C:/Dev/git/UbixOS/sys/vmm/paging.c File Reference
paging.c File Reference
#include <sys/types.h>
#include <vmm/vmm.h>
#include <lib/kprintf.h>
#include <lib/kmalloc.h>
#include <ubixos/kpanic.h>
#include <ubixos/sched.h>
#include <ubixos/spinlock.h>
#include <string.h>
#include <assert.h>
#include <sys/descrip.h>
#include <ubixos/vitals.h>
Functions
int obreak (struct thread *td, struct obreak_args *uap)
int vmm_cleanVirtualSpace (uint32_t addr)
int vmm_clearVirtualPage (uint32_t pageAddr)
void * vmm_getFreeKernelPage (pidType pid, uint16_t count)
void * vmm_getFreeMallocPage (uInt16 count)
void * vmm_mapFromTask (pidType pid, void *ptr, uint32_t size)
int vmm_pagingInit ()
int vmm_remapPage (uint32_t source, uint32_t dest, uint16_t perms, pidType pid, int haveLock)
Variables
uint32_t * kernelPageDirectory = 0x0
Function Documentation
obreak()
int obreak (struct thread * td, struct obreak_args * uap)
Definition at line 546 of file paging.c.
vmm_cleanVirtualSpace()
int vmm_cleanVirtualSpace (uint32_t addr)
Definition at line 587 of file paging.c.
Referenced by sysExec().
vmm_clearVirtualPage()
int vmm_clearVirtualPage (uint32_t pageAddr)
Definition at line 356 of file paging.c.
References PD_ENTRIES.
Referenced by vmm_getFreeKernelPage().
vmm_getFreeKernelPage()
void* vmm_getFreeKernelPage (pidType pid, uint16_t count)
Definition at line 291 of file paging.c.
References K_PANIC, KERNEL_PAGE_DEFAULT, kpanic(), PAGE_PRESENT, PAGE_SIZE, PD_BASE_ADDR, PD_ENTRIES, PD_INDEX, pdSpinLock, PT_BASE_ADDR, PT_ENTRIES, spinLock(), spinUnlock(), vmm_allocPageTable(), vmm_clearVirtualPage(), vmm_findFreePage(), VMM_KERN_END, VMM_KERN_START, and vmm_remapPage().
Referenced by biosCall(), and execThread().
vmm_getFreeMallocPage()
void* vmm_getFreeMallocPage (uInt16 count)
Definition at line 488 of file paging.c.
vmm_mapFromTask()
void* vmm_mapFromTask (pidType pid, void * ptr, uint32_t size)
Definition at line 372 of file paging.c.
Referenced by sdeThread().
vmm_pagingInit()
int vmm_pagingInit ()
Definition at line 58 of file paging.c.
References _vmm_pageFault(), bzero, K_PANIC, KERNEL_PAGE_DEFAULT, kernelPageDirectory, kprintf(), numPages, PAGE_DEFAULT, PAGE_GLOBAL, PAGE_SIZE, PAGE_STACK, PD_BASE_ADDR, PD_ENTRIES, PD_INDEX, PT_BASE_ADDR, sysID, vmm_findFreePage(), VMM_KERN_END, VMM_KERN_START, VMM_MMAP_ADDR_PMODE, VMM_MMAP_ADDR_RMODE, vmm_remapPage(), and vmmMemoryMap.
Referenced by vmm_init().
vmm_remapPage()
int vmm_remapPage (uint32_t source, uint32_t dest, uint16_t perms, pidType pid, int haveLock)
Definition at line 199 of file paging.c.
References K_PANIC, kpanic(), spinLock(), sysID, VMM_USER_END, and VMM_USER_START.
Referenced by elf_load_file(), execFile(), freebsd6_mmap(), kmod_load(), ldEnable(), ogDisplay_UbixOS::SetMode(), sys_mmap(), sysExec(), vmm_getFreeKernelPage(), and vmm_pagingInit().
Variable Documentation
kernelPageDirectory
uint32_t* kernelPageDirectory = 0x0
Definition at line 41 of file paging.c.
Referenced by biosCall(), execFile(), execThread(), and vmm_pagingInit().