UbixOS V2: C:/Dev/git/UbixOS/sys/pci/pci.c File Reference
pci.c File Reference
#include <pci/pci.h>
#include <sys/io.h>
#include <lib/kprintf.h>
Functions
int pci_init ()
uint32_t pciProbe (int bus, int dev, int func)
uInt32 pciRead (int bus, int dev, int func, int reg, int bytes)
void pciWrite (int bus, int dev, int func, int reg, uInt32 v, int bytes)
Variables
struct {
uInt8 baseClass
uInt8 interface
const char * name
uInt8 subClass
} pciClasses []
Function Documentation
pci_init()
int pci_init ()
Definition at line 244 of file pci.c.
References pciConfig::bus, pciConfig::classCode, countof, pciConfig::dev, pciConfig::func, pciConfig::intLine, pciConfig::intPin, kprintf(), name, pciClasses, pciProbe(), pciConfig::progIf, pciConfig::subClass, and pciConfig::vendorID.
pciProbe()
uint32_t pciProbe (int bus, int dev, int func)
Definition at line 139 of file pci.c.
References pciConfig::bar, pciConfig::bist, pciConfig::bus, pciConfig::cacheLineSize, pciConfig::classCode, pciConfig::command, pciConfig::dev, pciConfig::deviceID, pciConfig::func, pciConfig::headerType, pciConfig::intLine, pciConfig::intPin, kfree(), kmalloc(), kprintf(), pciConfig::latencyTimer, memset(), pciRead(), pciWrite(), pciConfig::progIf, pciConfig::status, pciConfig::subClass, and pciConfig::vendorID.
Referenced by pci_init().
pciRead()
uInt32 pciRead (int bus, int dev, int func, int reg, int bytes)
Definition at line 76 of file pci.c.
References confadd::bus, confadd::dev, confadd::enable, confadd::func, inportByte(), inportDWord(), inportWord(), outportDWord(), and confadd::reg.
Referenced by pciProbe().
pciWrite()
void pciWrite (int bus, int dev, int func, int reg, uInt32 v, int bytes)
Definition at line 108 of file pci.c.
References confadd::bus, confadd::dev, confadd::enable, confadd::func, outportByte(), outportDWord(), outportWord(), and confadd::reg.
Referenced by pciProbe().
Variable Documentation
baseClass
uInt8 baseClass
Definition at line 34 of file pci.c.
interface
uInt8 interface
Definition at line 36 of file pci.c.
name
const char* name
Definition at line 37 of file pci.c.
Referenced by _initHardDisk(), fatfs_format(), lookup(), netif_find(), pci_init(), sysMpiPostMessage(), and ubixfs_cacheNew().
pciClasses
const { ... } pciClasses[]
Referenced by pci_init().
subClass
uInt8 subClass
Definition at line 35 of file pci.c.