UbixOS V2: C:/Dev/git/UbixOS/sys/kernel/signal.c File Reference
signal.c File Reference
#include <sys/signal.h>
#include <sys/sysproto_posix.h>
#include <sys/thread.h>
#include <lib/kprintf.h>
#include <assert.h>
Functions
int sys_sigaction (struct thread *td, struct sys_sigaction_args *args)
int sys_sigprocmask (struct thread *td, struct sys_sigprocmask_args *args)
Function Documentation
sys_sigaction()
int sys_sigaction (struct thread * td, struct sys_sigaction_args * args)
Definition at line 80 of file signal.c.
References sys_sigaction_args::act, memcpy(), sys_sigaction_args::oact, sys_sigaction_args::sig, thread::sigact, and thread::td_retval.
sys_sigprocmask()
int sys_sigprocmask (struct thread * td, struct sys_sigprocmask_args * args)
Definition at line 35 of file signal.c.
References __sigset::__bits, sys_sigprocmask_args::how, kprintf(), memcpy(), sys_sigprocmask_args::oset, sys_sigprocmask_args::set, SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK, thread::sigmask, and thread::td_retval.