UbixOS V2: C:/Dev/git/UbixOS/sys/include/ubixos/smp.h File Reference
smp.h File Reference
#include <sys/types.h>
Data Structures
struct cpuinfo_t
Functions
void apicMagic ()
void cpuid (uInt32, uInt32 *)
void cpuidDetect ()
uInt8 cpuInfo ()
uInt32 getEflags ()
void setEflags (uInt32)
void smpInit ()
Function Documentation
apicMagic()
void apicMagic ()
Definition at line 231 of file smp.c.
References ap_trampoline_end(), ap_trampoline_start(), kprintf(), and memcpy().
cpuid()
void cpuid (uInt32 , uInt32 *)
cpuidDetect()
void cpuidDetect ()
Definition at line 168 of file smp.c.
References getEflags(), kpanic(), and setEflags().
cpuInfo()
uInt8 cpuInfo ()
Definition at line 177 of file smp.c.
References getEflags(), kpanic(), setEflags(), and spinLock().
getEflags()
uInt32 getEflags ()
Definition at line 253 of file smp.c.
Referenced by cpuidDetect(), and cpuInfo().
setEflags()
void setEflags (uInt32)
Definition at line 263 of file smp.c.
Referenced by cpuidDetect(), and cpuInfo().
smpInit()
void smpInit ()
Definition at line 156 of file smp.c.
References spinLock().