UbixOS V2: C:/Dev/git/UbixOS/sys/fs/vfs/stat.c File Reference
stat.c File Reference
#include <ubixos/errno.h>
#include <sys/sysproto.h>
#include <vfs/stat.h>
#include <vfs/file.h>
#include <lib/kprintf.h>
#include <sys/descrip.h>
Functions
int _sys_stat (char *path, struct stat *sb, int flags)
int sys_fstat (struct thread *td, struct sys_fstat_args *args)
int sys_fstatat (struct thread *td, struct sys_fstatat_args *args)
int sys_fstatfs (struct thread *td, struct sys_fstatfs_args *args)
int sys_lstat (struct thread *td, struct sys_lstat_args *args)
int sys_stat (struct thread *td, struct sys_stat_args *args)
int sys_statfs (struct thread *td, struct sys_statfs_args *args)
Function Documentation
_sys_stat()
int _sys_stat (char * path, struct stat * sb, int flags)
Definition at line 36 of file stat.c.
References ufs2_dinode::di_atime, ufs2_dinode::di_ctime, ufs2_dinode::di_gid, ufs2_dinode::di_mode, ufs2_dinode::di_mtime, ufs2_dinode::di_nlink, ufs2_dinode::di_size, ufs2_dinode::di_uid, fclose(), fopen(), fileDescriptor::ino, fileDescriptor::inode, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, inode::u, and inode::ufs2_i.
Referenced by sys_lstat(), and sys_stat().
sys_fstat()
int sys_fstat (struct thread * td, struct sys_fstat_args * args)
Definition at line 91 of file stat.c.
References ufs2_dinode::di_atime, ufs2_dinode::di_ctime, ufs2_dinode::di_gid, ufs2_dinode::di_mode, ufs2_dinode::di_mtime, ufs2_dinode::di_nlink, ufs2_dinode::di_size, ufs2_dinode::di_uid, file::fd, sys_fstat_args::fd, getfd(), fileDescriptor::ino, fileDescriptor::inode, fileDescriptor::res, sys_fstat_args::sb, fileDescriptor::size, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, thread::td_retval, inode::u, and inode::ufs2_i.
sys_fstatat()
int sys_fstatat (struct thread * td, struct sys_fstatat_args * args)
Definition at line 133 of file stat.c.
References sys_fstatat_args::buf, ufs2_dinode::di_atime, ufs2_dinode::di_ctime, ufs2_dinode::di_gid, ufs2_dinode::di_mode, ufs2_dinode::di_mtime, ufs2_dinode::di_nlink, ufs2_dinode::di_size, ufs2_dinode::di_uid, fclose(), file::fd, sys_fstatat_args::fd, fopen(), getfd(), fileDescriptor::ino, fileDescriptor::inode, sys_fstatat_args::path, stat::st_atime, stat::st_ctime, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_mtime, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, strlen(), thread::td_retval, inode::u, and inode::ufs2_i.
sys_fstatfs()
int sys_fstatfs (struct thread * td, struct sys_fstatfs_args * args)
Definition at line 182 of file stat.c.
References sys_fstatfs_args::buf, statfs::f_asyncreads, statfs::f_asyncwrites, statfs::f_bavail, statfs::f_bfree, statfs::f_blocks, statfs::f_bsize, statfs::f_ffree, statfs::f_files, statfs::f_flags, statfs::f_fsid, statfs::f_fstypename, statfs::f_iosize, statfs::f_mntfromname, statfs::f_mntonname, statfs::f_namemax, statfs::f_owner, statfs::f_syncreads, statfs::f_syncwrites, statfs::f_type, statfs::f_version, file::fd, sys_fstatfs_args::fd, getfd(), sprintf(), thread::td_retval, and fsid::val.
sys_lstat()
int sys_lstat (struct thread * td, struct sys_lstat_args * args)
Definition at line 297 of file stat.c.
References _sys_stat(), sys_lstat_args::path, sys_lstat_args::sb, STAT_LSTAT, and thread::td_retval.
sys_stat()
int sys_stat (struct thread * td, struct sys_stat_args * args)
Definition at line 302 of file stat.c.
References _sys_stat(), sys_stat_args::path, STAT_LSTAT, thread::td_retval, and sys_stat_args::ub.
sys_statfs()
int sys_statfs (struct thread * td, struct sys_statfs_args * args)
Definition at line 239 of file stat.c.
References sys_statfs_args::buf, statfs::f_asyncreads, statfs::f_asyncwrites, statfs::f_bavail, statfs::f_bfree, statfs::f_blocks, statfs::f_bsize, statfs::f_ffree, statfs::f_files, statfs::f_flags, statfs::f_fsid, statfs::f_fstypename, statfs::f_iosize, statfs::f_mntfromname, statfs::f_mntonname, statfs::f_namemax, statfs::f_owner, statfs::f_syncreads, statfs::f_syncwrites, statfs::f_type, statfs::f_version, file::fd, fopen(), sys_statfs_args::path, sprintf(), thread::td_retval, and fsid::val.