UbixOS V2: device_interface Struct Reference
device_interface Struct Reference
#include <device.h>
Data Fields
void * info
int(* init)(void *)
uInt8 initialized
void(* ioctl)(void *)
int major
int(* read)(void *, void *, uInt32, uInt32)
void(* reset)(void *)
uInt32 size
void(* standby)(void *)
void(* start)(void *)
void(* stop)(void *)
int(* write)(void *, void *, uInt32, uInt32)
Detailed Description
Definition at line 47 of file device.h.
Field Documentation
info
void* device_interface::info
Definition at line 51 of file device.h.
Referenced by gptfind(), hdInit(), media_read(), media_write(), syncBat(), ubixfs_initialize(), ubixFSmkDir(), writeFileByte(), and writeUbixFS().
init
int(* device_interface::init) (void *)
Definition at line 55 of file device.h.
Referenced by fdc_init().
initialized
uInt8 device_interface::initialized
Definition at line 48 of file device.h.
Referenced by hdInit().
ioctl
void(* device_interface::ioctl) (void *)
Definition at line 56 of file device.h.
major
int device_interface::major
Definition at line 50 of file device.h.
Referenced by fdc_init().
read
int(* device_interface::read) (void *, void *, uInt32, uInt32)
Definition at line 52 of file device.h.
Referenced by fdc_init(), media_read(), open_fat(), ubixfs_initialize(), writeFileByte(), and writeUbixFS().
reset
void(* device_interface::reset) (void *)
Definition at line 54 of file device.h.
Referenced by fdc_init().
size
uInt32 device_interface::size
Definition at line 49 of file device.h.
Referenced by fdcInit2(), and hdInit().
standby
void(* device_interface::standby) (void *)
Definition at line 59 of file device.h.
start
void(* device_interface::start) (void *)
Definition at line 58 of file device.h.
stop
void(* device_interface::stop) (void *)
Definition at line 57 of file device.h.
write
int(* device_interface::write) (void *, void *, uInt32, uInt32)
Definition at line 53 of file device.h.
Referenced by fdc_init(), media_write(), syncBat(), ubixFSmkDir(), writeFileByte(), and writeUbixFS().
The documentation for this struct was generated from the following file:
C:/Dev/git/UbixOS/sys/include/sys/device.h