UbixOS V2: C:/Dev/git/UbixOS/sys/kernel/syscall_posix.c File Reference
syscall_posix.c File Reference
#include <ubixos/syscalls.h>
#include <ubixos/syscall.h>
#include <ubixos/sched.h>
#include <ubixos/endtask.h>
#include <ubixos/spinlock.h>
#include <sys/trap.h>
#include <sys/elf.h>
#include <string.h>
#include <lib/kprintf.h>
#include <ubixos/kpanic.h>
Functions
int invalidCall_posix ()
void sys_call_posix (struct trapframe *frame)
Variables
struct spinLock Master = SPIN_LOCK_INITIALIZER
Function Documentation
invalidCall_posix()
int invalidCall_posix ()
Definition at line 124 of file syscall_posix.c.
References _current, taskStruct::id, kprintf(), and sys_call().
sys_call_posix()
void sys_call_posix (struct trapframe * frame)
Definition at line 42 of file syscall_posix.c.
References _current, thread::abi, die_if_kernel(), ELFOSABI_FREEBSD, thread::frame, taskStruct::id, kpanic(), kprintf(), memcpy(), PSL_C, syscall_entry::sc_name, SYSCALL_DUMMY, SYSCALL_INVALID, SYSCALL_NOTIMP, systemCalls, systemCalls_posix, taskStruct::td, thread::td_retval, trapframe::tf_eax, trapframe::tf_edx, trapframe::tf_eflags, trapframe::tf_esp, and totalCalls_posix.
Variable Documentation
Master
struct spinLock Master = SPIN_LOCK_INITIALIZER
Definition at line 40 of file syscall_posix.c.