UbixOS V2: C:/Dev/git/UbixOS/sys/include/sys/sysproto.h File Reference
sysproto.h File Reference
#include <sys/thread.h>
Data Structures
struct sys_mpiCreateMbox_args
struct sys_mpiDestroyMbox_args
struct sys_mpiFetchMessage_args
struct sys_mpiPostMessage_args
struct sys_sde_args
Macros
#define PAD_(t) (sizeof(register_t) <= sizeof(t) ? 0 : sizeof(register_t) - sizeof(t))
#define PADL_(t) 0
#define PADR_(t) PAD_(t)
Typedefs
typedef int register_t
Functions
int sys_invalid (struct thread *, void *)
int sys_mpiCreateMbox (struct thread *, struct sys_mpiCreateMbox_args *)
int sys_mpiDestroyMbox (struct thread *, struct sys_mpiDestroyMbox_args *)
int sys_mpiFetchMessage (struct thread *, struct sys_mpiFetchMessage_args *)
int sys_mpiPostMessage (struct thread *, struct sys_mpiPostMessage_args *)
Macro Definition Documentation
PAD_
#define PAD_ (t) (sizeof(register_t) <= sizeof(t) ? 0 : sizeof(register_t) - sizeof(t))
Definition at line 36 of file sysproto.h.
PADL_
#define PADL_ (t) 0
Definition at line 39 of file sysproto.h.
PADR_
#define PADR_ (t) PAD_(t)
Definition at line 40 of file sysproto.h.
Typedef Documentation
register_t
typedef int register_t
Definition at line 34 of file sysproto.h.
Function Documentation
sys_invalid()
int sys_invalid (struct thread * , void *)
Definition at line 141 of file gen_calls.c.
sys_mpiCreateMbox()
int sys_mpiCreateMbox (struct thread * , struct sys_mpiCreateMbox_args *)
Definition at line 4 of file mpi_syscalls.c.
References mpi_createMbox(), sys_mpiCreateMbox_args::name, and thread::td_retval.
sys_mpiDestroyMbox()
int sys_mpiDestroyMbox (struct thread * , struct sys_mpiDestroyMbox_args *)
Definition at line 9 of file mpi_syscalls.c.
References mpi_destroyMbox(), sys_mpiDestroyMbox_args::name, and thread::td_retval.
sys_mpiFetchMessage()
int sys_mpiFetchMessage (struct thread * , struct sys_mpiFetchMessage_args *)
Definition at line 14 of file mpi_syscalls.c.
References mpi_fetchMessage(), sys_mpiFetchMessage_args::msg, sys_mpiFetchMessage_args::name, and thread::td_retval.
sys_mpiPostMessage()
int sys_mpiPostMessage (struct thread * , struct sys_mpiPostMessage_args *)
Definition at line 19 of file mpi_syscalls.c.
References kprintf(), mpi_postMessage(), sys_mpiPostMessage_args::msg, sys_mpiPostMessage_args::name, thread::td_retval, and sys_mpiPostMessage_args::type.