UbixOS V2: C:/Dev/git/UbixOS/sys/mpi/system.c File Reference
system.c File Reference
#include <mpi/mpi.h>
#include <lib/kmalloc.h>
#include <string.h>
#include <ubixos/spinlock.h>
#include <sys/sysproto.h>
Functions
int mpi_createMbox (char *name)
int mpi_destroyMbox (char *name)
int mpi_fetchMessage (char *name, mpi_message_t *msg)
int mpi_postMessage (char *name, uint32_t type, mpi_message_t *msg)
int mpi_spam (uInt32 type, void *data)
Function Documentation
mpi_createMbox()
int mpi_createMbox (char * name)
Definition at line 68 of file system.c.
Referenced by sys_mpiCreateMbox(), and systemTask().
mpi_destroyMbox()
int mpi_destroyMbox (char * name)
Definition at line 231 of file system.c.
Referenced by sys_mpiDestroyMbox().
mpi_fetchMessage()
int mpi_fetchMessage (char * name, mpi_message_t * msg)
Definition at line 187 of file system.c.
Referenced by sys_mpiFetchMessage(), and systemTask().
mpi_postMessage()
int mpi_postMessage (char * name, uint32_t type, mpi_message_t * msg)
Definition at line 141 of file system.c.
mpi_spam()
int mpi_spam (uInt32 type, void * data)
Definition at line 107 of file system.c.