UbixOS V2: C:/Dev/git/UbixOS/sys/include/ubixos/time.h File Reference
time.h File Reference
#include <sys/types.h>
#include <sys/_timespec.h>
#include <sys/io.h>
Data Structures
struct timeStruct
struct timezone
Macros
#define BCD_TO_BIN(val) ((val)=((val)&15) + ((val)>>4)*10)
#define DAY (24*HOUR)
#define HOUR (60*MINUTE)
#define MINUTE 60
#define YEAR (365*DAY)
Typedefs
typedef long suseconds_t
Functions
int gettimeofday (struct timeval *tp, struct timezone *tzp)
int time_init ()
uInt32 timeMake (struct timeStruct *time)
Macro Definition Documentation
BCD_TO_BIN
#define BCD_TO_BIN (val) ((val)=((val)&15) + ((val)>>4)*10)
Definition at line 38 of file time.h.
DAY
#define DAY (24*HOUR)
Definition at line 42 of file time.h.
HOUR
#define HOUR (60*MINUTE)
Definition at line 41 of file time.h.
MINUTE
#define MINUTE 60
Definition at line 40 of file time.h.
YEAR
#define YEAR (365*DAY)
Definition at line 43 of file time.h.
Typedef Documentation
suseconds_t
typedef long suseconds_t
Definition at line 36 of file time.h.
Function Documentation
gettimeofday()
int gettimeofday (struct timeval * tp, struct timezone * tzp)
Definition at line 110 of file time.c.
References systemVitals, vitalsStruct::sysUptime, vitalsStruct::timeStart, timeval::tv_sec, timeval::tv_usec, timezone::tz_dsttime, and timezone::tz_minuteswest.
Referenced by sys_gettimeofday(), sys_init(), and sys_unix_now().
time_init()
int time_init ()
Definition at line 52 of file time.c.
timeMake()
uInt32 timeMake (struct timeStruct * time)
Definition at line 87 of file time.c.
References DAY, YEAR, and timeStruct::year.