UbixOS V2: C:/Dev/git/UbixOS/sys/kernel/tty.c File Reference
tty.c File Reference
#include <ubixos/tty.h>
#include <ubixos/kpanic.h>
#include <ubixos/spinlock.h>
#include <lib/kprintf.h>
#include <lib/kmalloc.h>
#include <sys/io.h>
#include <string.h>
Functions
int tty_change (uInt16 tty)
tty_term * tty_find (uInt16 tty)
int tty_init ()
int tty_print (char *string, tty_term *term)
Variables
tty_term * tty_foreground = 0x0
Function Documentation
tty_change()
int tty_change (uInt16 tty)
Definition at line 84 of file tty.c.
References kpanic(), memcpy(), tty_termNode::tty_buffer, tty_foreground, and TTY_MAX_TERMS.
tty_find()
tty_term* tty_find (uInt16 tty)
Definition at line 167 of file tty.c.
Referenced by execFile(), kprint(), and systemTask().
tty_init()
int tty_init ()
Definition at line 41 of file tty.c.
tty_print()
int tty_print (char * string, tty_term * term)
Definition at line 115 of file tty.c.
References spinLock().
Referenced by kprint(), sys_fwrite(), and sysFwrite().
Variable Documentation
tty_foreground
tty_term* tty_foreground = 0x0
Definition at line 38 of file tty.c.
Referenced by getchar(), kpanic(), kprint(), sys_fgetc(), sys_pread(), sys_read(), and tty_change().