UbixOS V2: C:/Dev/git/UbixOS/sys/net/net/udpecho.c File Reference
udpecho.c File Reference
#include <sys/types.h>
#include <lib/kprintf.h>
#include "net/api.h"
#include "net/sys.h"
Functions
void udpecho_init (void)
void udpecho_thread (void *arg)
Function Documentation
udpecho_init()
void udpecho_init (void)
Definition at line 64 of file udpecho.c.
References NULL, sys_thread_new(), and udpecho_thread().
udpecho_thread()
void udpecho_thread (void * arg)
Definition at line 43 of file udpecho.c.
References buffer, and NULL.
Referenced by udpecho_init().