UbixOS V2: C:/Dev/git/UbixOS/sys/include/sys/video.h File Reference
video.h File Reference
#include <sys/types.h>
Macros
#define defaultColor 0x0F
Functions
void backSpace ()
void clearScreen ()
void kprint (char *string)
Variables
int printColor
Macro Definition Documentation
defaultColor
#define defaultColor 0x0F
Definition at line 34 of file video.h.
Function Documentation
backSpace()
void backSpace ()
Definition at line 37 of file video.c.
References inportByte(), and outportByte().
clearScreen()
void clearScreen ()
Definition at line 109 of file video.c.
kprint()
void kprint (char * string)
Definition at line 58 of file video.c.
References inportByte(), NULL, outportByte(), tty_find(), tty_foreground, and tty_print().
Referenced by kprintf().
Variable Documentation
printColor
int printColor
Definition at line 35 of file video.c.
Referenced by sys_write().