UbixOS: include/ubixos/syscall_posix.h File Reference
syscall_posix.h File Reference
#include <sys/trap.h>
Functions
void _sys_call_posix ()
void sys_call_posix (struct trapframe *frame)
Function Documentation
_sys_call_posix()
void _sys_call_posix ()
sys_call_posix()
void sys_call_posix (struct trapframe * frame)
Definition at line 42 of file syscall_posix.c.
References _current, thread::abi, die_if_kernel(), ELFOSABI_FREEBSD, thread::frame, taskStruct::id, kpanic(), kprintf(), memcpy(), PSL_C, syscall_entry::sc_name, SYSCALL_DEBUG, SYSCALL_DUMMY, SYSCALL_INVALID, SYSCALL_NOTIMP, systemCalls, systemCalls_posix, taskStruct::td, thread::td_retval, trapframe::tf_eax, trapframe::tf_edx, trapframe::tf_eflags, trapframe::tf_esp, and totalCalls_posix.