# $Id$
# The System Makefile (C) 2002 The UbixOS Project

all: 
	(cd btree;make)
	(cd db;make)
	(cd hash;make)
	(cd mpool;make)
	(cd recno;make)

# Clean up the junk
clean:
	(cd btree;make clean)
	(cd db;make clean)
	(cd hash;make clean)
	(cd mpool;make clean)
	(cd recno;make clean)
