# (C) 2002-2026 The UbixOS Project

include ../../../../Makefile.incl
include ../../../Makefile.incl

INCLUDES += -I../../../include

OBJS = dhcp6.o ethip6.o icmp6.o inet6.o ip6.o ip6_addr.o ip6_frag.o mld6.o nd6.o

.include "${UBIX_MK}/ubix.kern.mk"
