# bin/files/Makefile — Files, the graphical file manager (views + objGFX).
include ../../Makefile.incl
include ../Makefile.incl

BINARY = files
OBJS   = main.o
SRCS   = main.cc

.include "${UBIX_MK}/ubix.musl.cxx.ubix.prog.mk"
