UbixOS: vmm/setpageattributes.c File Reference
setpageattributes.c File Reference
#include <vmm/vmm.h>
#include <ubixos/kpanic.h>
Functions
int vmm_setPageAttributes (uint32_t memAddr, uint16_t attributes)
Function Documentation
vmm_setPageAttributes()
int vmm_setPageAttributes (uint32_t memAddr, uint16_t attributes)
Definition at line 39 of file setpageattributes.c.
References kpanic(), and PT_BASE_ADDR.
Referenced by elf_load_file(), execFile(), and sysExec().