# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

INCLUDES += -I../include

OBJS = strtol.o atoi.o abs.o exit.o malloc.o rand.o getopt.o getenv.o setenv.o

.include "${UBIX_MK}/ubix.sublib.mk"
