UbixOS: vmm/getfreevirtualpage.c File Reference
getfreevirtualpage.c File Reference
#include <vmm/vmm.h>
#include <ubixos/sched.h>
#include <ubixos/kpanic.h>
#include <ubixos/spinlock.h>
#include <lib/kprintf.h>
Functions
void * vmm_getFreeVirtualPage (pidType pid, int count, int type)
Function Documentation
vmm_getFreeVirtualPage()
void* vmm_getFreeVirtualPage (pidType pid, int count, int type)
Definition at line 47 of file getfreevirtualpage.c.
References spinLock().
Referenced by sys_mmap(), and sysGetFreePage().