UbixOS: arch/i386/systemtask.c File Reference
systemtask.c File Reference
#include <ubixos/systemtask.h>
#include <ubixos/kpanic.h>
#include <ubixos/exec.h>
#include <ubixos/tty.h>
#include <ubixos/sched.h>
#include <ubixos/vitals.h>
#include <lib/kmalloc.h>
#include <lib/kprintf.h>
#include <lib/bioscall.h>
#include <sde/sde.h>
#include <sys/shutdown.h>
#include <vmm/vmm.h>
#include <mpi/mpi.h>
#include <string.h>
Functions
void systemTask ()
Function Documentation
systemTask()
void systemTask ()
Definition at line 46 of file systemtask.c.
References biosCall(), mpi_message::data, execThread(), fclose(), taskStruct::files, mpi_message::header, taskStruct::id, inportByte(), kfree(), kpanic(), kprintf(), mpi_createMbox(), mpi_fetchMessage(), ogprintOff, outportByte(), mpi_message::pid, printOff, REBOOT, sched_getDelTask(), sched_yield(), schedFindTask(), sdeThread(), strcmp(), sys_shutdown(), systemVitals, vitalsStruct::sysUptime, taskStruct::term, tty_find(), and vmm_freeProcessPages().