# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

OBJS = fat.o fat_access.o fat_cache.o fat_filelib.o fat_format.o fat_fread.o fat_misc.o fat_string.o fat_table.o fat_write.o

.include "${UBIX_MK}/ubix.kern.mk"
