# (C) 2002-2026 The UbixOS Project

include ../../../Makefile.incl
include ../../Makefile.incl

OBJS = fat_bpb.o fat_sector.o fat_clust.o fat_dir.o fat_file.o fat_vfs.o

.include "${UBIX_MK}/ubix.kern.mk"
