UbixOS: vmm/getphysicaladdr.c File Reference
getphysicaladdr.c File Reference
#include <vmm/vmm.h>
Functions
uint32_t vmm_getPhysicalAddr (uint32_t pageAddr)
uint32_t vmm_getRealAddr (uint32_t addr)
Function Documentation
vmm_getPhysicalAddr()
uint32_t vmm_getPhysicalAddr (uint32_t pageAddr)
Function: void *vmm_getPhysicalAddr(); Description: Returns The Physical Address Of The Virtual Page Notes:
Definition at line 38 of file getphysicaladdr.c.
References PT_BASE_ADDR.
Referenced by vmm_createVirtualSpace().
vmm_getRealAddr()
uint32_t vmm_getRealAddr (uint32_t addr)
Definition at line 56 of file getphysicaladdr.c.
References PT_BASE_ADDR.
Referenced by initLNC(), and lncAttach().