UbixOS: fs/fat/example.c File Reference
example.c File Reference
#include <stdio.h>
#include "fat_filelib.h"
Functions
void main ()
int media_init ()
int media_read (unsigned long sector, unsigned char *buffer, unsigned long sector_count)
int media_write (unsigned long sector, unsigned char *buffer, unsigned long sector_count)
Function Documentation
main()
void main ()
Definition at line 44 of file example.c.
References FAT_INIT_OK, file, fl_attach_media(), fl_fclose(), fl_fopen(), fl_fwrite(), fl_init(), fl_listdirectory(), fl_remove(), fl_shutdown(), media_init(), media_read(), and media_write().
media_init()
int media_init ()
Definition at line 4 of file example.c.
Referenced by main().
media_read()
int media_read (unsigned long sector, unsigned char * buffer, unsigned long sector_count)
Definition at line 10 of file example.c.
References buffer.
Referenced by main().
media_write()
int media_write (unsigned long sector, unsigned char * buffer, unsigned long sector_count)
Definition at line 27 of file example.c.
References buffer.
Referenced by main().